<?php

declare(strict_types=1);

namespace Xors3D\Controllers;

use Xors3D\Core\Controller;
use Xors3D\Ffi\Constants;
use Xors3D\Ffi\Engine;
use Xors3D\Scene\MouseLookCamera;

/**
 * "Craft" - a Minecraft-like voxel game for Xors3d (PHP / FFI).
 *
 * Menu:      Play / New World / Save World / Load World / Settings / Quit
 * Settings:  sensitivity, invert-Y, FOV, fog, day/night, sound volume,
 *            resolution, vsync, world size, tree density, water
 * Game:      WASD + mouse, F = fly/walk toggle, SPACE jump (walk) or up (fly),
 *            SHIFT down (fly), LMB destroy, RMB place, 1-9 / mouse wheel = block,
 *            Esc = menu.
 *
 * Features: procedural world + biomes (grass/sand beach/snow caps), trees,
 * animated translucent water, walking with gravity + voxel collision, a held
 * block ("hand"), save/load, and synthesized sound (break/place/steps/ambient).
 *
 * Textures are real 16x16 Minecraft tiles in assets/blocks/; sounds are
 * generated by bin/gen_sounds.php into assets/sounds/.
 */
final class MinecraftController extends Controller
{
    public const TITLE = 'Minecraft-like game (menu, walk, water, sound)';

    private const MAX_H = 11;
    private const SNOW  = 9;
    private const SEA   = 3;
    private const Y_MAX = 48;
    private const BLOCK = 2.0;
    private const CH    = 8;      // chunk size (columns) for render-distance culling

    // player physics (world units)
    private const G     = 0.03;
    private const JUMP  = 0.55;
    private const PH    = 3.0;   // player height
    private const EYE   = 2.6;   // eye height above feet
    private const HW    = 0.55;  // player half width
    private const SPD_WALK = 0.20;
    private const SPD_FLY  = 0.55;

    private const RESOLUTIONS = [
        [800, 600], [1024, 768], [1280, 720], [1366, 768], [1600, 900], [1920, 1080],
    ];

    /** Block type id => [name, texture file]. */
    private const TYPES = [
        1  => ['Grass',     'grass.png'],
        2  => ['Dirt',      'dirt.png'],
        3  => ['Stone',     'stone.png'],
        4  => ['Brick',     'brick.png'],
        5  => ['Wood',      'wood.png'],
        6  => ['Snow',      'snow.png'],
        7  => ['Leaves',    'leaves.png'],
        8  => ['Log',       'log.png'],
        9  => ['Sand',      'sand.png'],
        10 => ['Glass',     'glass.png'],
        11 => ['Glowstone', 'glowstone.png'],
        12 => ['Diamond',   'diamond_ore.png'],
        13 => ['Coal',      'coal.png'],
        14 => ['Iron',      'iron.png'],
    ];

    /** Selectable blocks (hotbar / wheel), by type id. */
    private const HOTBAR = [1, 2, 3, 4, 5, 9, 10, 11, 12];

    /** @var array<string,int|float> */
    private array $settings = [
        'width' => 1024, 'height' => 768, 'vsync' => 1,
        'sensitivity' => 0.5, 'invertY' => 0, 'fov' => 1.0,
        'fog' => 1, 'daynight' => 1, 'volume' => 0.8, 'renderDist' => 24,
        'bloom' => 0, 'godrays' => 1,
        'worldSize' => 96, 'trees' => 1.0, 'water' => 1, 'mobs' => 8,
    ];

    private const OPTIONS = [
        ['key' => 'sensitivity', 'label' => 'Mouse sensitivity', 'type' => 'float', 'min' => 0.1, 'max' => 2.0, 'step' => 0.05],
        ['key' => 'invertY',     'label' => 'Invert mouse Y',    'type' => 'bool'],
        ['key' => 'fov',         'label' => 'Field of view',     'type' => 'float', 'min' => 0.6, 'max' => 1.6, 'step' => 0.1],
        ['key' => 'fog',         'label' => 'Fog',               'type' => 'bool'],
        ['key' => 'daynight',    'label' => 'Day/night cycle',   'type' => 'bool'],
        ['key' => 'bloom',       'label' => 'Bloom (shader)',    'type' => 'bool'],
        ['key' => 'godrays',     'label' => 'Sun rays (shader)', 'type' => 'bool'],
        ['key' => 'volume',      'label' => 'Sound volume',      'type' => 'float', 'min' => 0.0, 'max' => 1.0, 'step' => 0.1],
        ['key' => 'renderDist',  'label' => 'Render distance',   'type' => 'int',  'min' => 16, 'max' => 96, 'step' => 8],
        ['key' => 'resolution',  'label' => 'Resolution',        'type' => 'res',  'note' => 'restart'],
        ['key' => 'vsync',       'label' => 'VSync',             'type' => 'bool', 'note' => 'restart'],
        ['key' => 'trees',       'label' => 'Tree density',      'type' => 'float', 'min' => 0.0, 'max' => 3.0, 'step' => 0.5, 'note' => 'new world'],
        ['key' => 'water',       'label' => 'Water',             'type' => 'bool', 'note' => 'new world'],
        ['key' => 'mobs',        'label' => 'Sheep count',       'type' => 'int',  'min' => 0, 'max' => 16, 'step' => 1, 'note' => 'new world'],
    ];

    private Engine $e;
    private MouseLookCamera $cam;
    private int $camH = 0;
    private int $pivot = 0;
    private int $sun = 0;
    private string $status = '';
    private bool $quit = false;

    private int $wsize = 20;
    private float $scale = 1.0;
    private int $slot = 0;           // hotbar index
    private int $hand = 0;
    private bool $fly = false;

    // player state (feet position, world units)
    private float $px = 0.0;
    private float $py = 0.0;
    private float $pz = 0.0;
    private float $vy = 0.0;
    private bool $onGround = false;
    private int $lastStep = 0;
    private int $mobTimer = 0;

    /** @var array<int,int> */ private array $template = [];
    /** @var array<int,int> */ private array $tex = [];
    private int $waterTpl = 0;
    private int $waterTex = 0;
    /** @var array<int,bool> water entity handle => true */ private array $water = [];
    /** @var array<int,array<int,int>> */ private array $height = [];

    // streaming chunks + edit overlay (generative world)
    /** @var array<string,int[]> "cx,cz" => entity handles (mesh + water) */ private array $chunk = [];
    /** @var array<string,bool> loaded chunk keys */ private array $loaded = [];
    /** @var array<string,int> "x,y,z" => type (0 = removed): tree + player edits over generated world */ private array $edits = [];
    /** @var array<string,array<string,int>> chunk key => its edits */ private array $editsByChunk = [];
    /** @var array<string,bool> chunks whose trees have been generated */ private array $treeGen = [];
    /** @var array<int,int> block type => brush (textured) for chunk meshes */ private array $brush = [];
    /** @var array<string,int> chunk key => merged mesh handle */ private array $chunkMesh = [];
    /** @var array<int,string> mesh handle => chunk key (for picking) */ private array $meshCk = [];
    private int $streamCX = PHP_INT_MAX;
    private int $streamCZ = PHP_INT_MAX;
    private float $originX = 0.0;   // player home (world units), for mobs/backdrop
    private float $originZ = 0.0;

    private float $seed = 0.0;
    private int $sunDisc = 0;
    private int $moonDisc = 0;
    private int $moon = 0;   // night directional light
    private float $dayF = 1.0; // 0 night .. 1 noon (for tinting sky objects)
    /** @var array<int,array<string,mixed>> drifting cloud slabs */
    private array $clouds = [];
    /** @var int[] all cloud puff sprite handles (for day/night tinting) */
    private array $cloudPuffs = [];
    /** @var array<int,int> hotbar type id => 2D icon image handle */
    private array $icon = [];
    /** @var array<string,int> mob part textures */
    private array $mobTex = [];
    /** @var array<int,array<string,mixed>> active sheep mobs */
    private array $mobs = [];

    // bloom post-effect (shader)
    private int $bloomPoly = 0;
    private int $bloomTexS = 0;
    private int $bloomTexF = 0;
    private int $bloomFX = 0;
    private bool $bloomOK = false;

    // god-rays post-effect (shader)
    private int $godPoly = 0;
    private int $godTex = 0;
    private int $godFX = 0;
    private bool $godOK = false;

    // sounds
    private int $sndBreak = 0;
    private int $sndPlace = 0;
    private int $sndStep = 0;
    private int $sndAmbient = 0;
    private int $ambCh = 0;

    // ===================================================================== run

    public function index(int|string $maxFrames = 0): int
    {
        $max = (int) $maxFrames;
        $e = $this->e = $this->engine;

        $this->loadSettings();

        $e->xKey($this->config->firstKey());
        $e->xSetAntiAliasType($e->xGetMaxAntiAlias());
        $e->xAppTitle('Craft - Xors3d voxel game (PHP)');
        $e->xGraphics3D((int) $this->settings['width'], (int) $this->settings['height'], 32, 0, (int) $this->settings['vsync']);
        $e->xAntiAlias(1);
        $e->xSetTextureFiltering(Constants::TF_POINT);
        $e->xHidePointer();

        $this->cam = new MouseLookCamera($e);
        $this->camH = $this->cam->handle();
        $e->xCameraClsColor($this->camH, 140, 190, 235);
        $e->xCameraRange($this->camH, 0.2, 600);
        $e->xCameraFogColor($this->camH, 140, 190, 235);
        $e->xCameraFogRange($this->camH, 60, 260);

        $this->sun = $e->xCreateLight(Constants::LIGHT_DIRECTIONAL);
        $e->xRotateEntity($this->sun, 50, 30, 0);
        $this->moon = $e->xCreateLight(Constants::LIGHT_DIRECTIONAL);
        $e->xRotateEntity($this->moon, 230, 30, 0);
        $e->xLightColor($this->moon, 0, 0, 0);
        $e->xAmbientLight(120, 120, 130);
        $e->xLoadFont('Arial', 14);

        $this->buildTemplates($e);
        $this->loadIcons($e);
        $this->loadMobTextures($e);
        $this->createSky($e);
        $this->createHand($e, $this->camH);
        $this->pivot = $e->xCreatePivot();
        $this->loadSounds($e);
        $this->setupBloom($e);
        $this->setupGodRays($e);
        $this->applySettings();
        $this->rebuildWorld();

        if ($max > 0) {
            $this->spawnPlayer();
            $this->gameLoop($max);
            $e->xReleaseGraphics();
            return 0;
        }

        if (getenv('CRAFT_SETSHOT')) { $this->settingsMenu(); $e->xReleaseGraphics(); return 0; }

        while (!$this->quit) {
            $action = $this->mainMenu();
            if ($this->quit || $action === 'quit') {
                break;
            }
            if ($action === 'save')     { $this->saveWorld(); continue; }
            if ($action === 'load')     { $this->loadWorld(); continue; }
            if ($action === 'settings') { $this->settingsMenu(); continue; }
            if ($action === 'new')      { $this->rebuildWorld(); $this->status = 'New world generated.'; }
            $this->spawnPlayer();
            $this->gameLoop(0);
        }

        $e->xReleaseGraphics();
        return 0;
    }

    // ================================================================= helpers

    private function closeRequested(): bool
    {
        return (bool) $this->e->xWinMessage('WM_CLOSE');
    }

    private function selectedType(): int
    {
        return self::HOTBAR[$this->slot];
    }

    private function spawnPlayer(): void
    {
        $this->px = $this->originX;
        $this->pz = $this->originZ;
        $this->py = (self::MAX_H + 6) * self::BLOCK;
        $this->vy = 0.0;
        $this->onGround = false;
        $this->cam->reset();
        $this->e->xPositionEntity($this->camH, $this->px, $this->py + self::EYE, $this->pz);
        $this->streamCX = PHP_INT_MAX;              // force streaming refresh
        $this->updateStreaming($this->px, $this->pz); // build the world around spawn
        $this->clearMobs();                        // sheep re-stream around the new spot
        $this->mobTimer = 0;
        $seed = min(4, (int) $this->settings['mobs']);
        for ($i = 0; $i < $seed; $i++) { $this->spawnMobNear(); } // a few right away
    }

    // ================================================================ settings

    private function settingsFile(): string { return dirname(__DIR__, 2) . '/craft-settings.json'; }

    private function loadSettings(): void
    {
        $f = $this->settingsFile();
        if (is_file($f) && ($json = json_decode((string) file_get_contents($f), true)) !== null) {
            foreach ($this->settings as $k => $v) {
                if (isset($json[$k])) {
                    $this->settings[$k] = is_float($v) ? (float) $json[$k] : (is_int($v) ? (int) $json[$k] : $json[$k]);
                }
            }
        }
    }

    private function saveSettings(): void
    {
        @file_put_contents($this->settingsFile(), json_encode($this->settings, JSON_PRETTY_PRINT));
    }

    private function applySettings(): void
    {
        $this->cam->setSensitivity((float) $this->settings['sensitivity']);
        $this->cam->setInvertY((bool) $this->settings['invertY']);
        $this->e->xCameraZoom($this->camH, (float) $this->settings['fov']);
        $this->e->xCameraFogMode($this->camH, (int) $this->settings['fog'] ? 1 : 0);
        if ($this->ambCh !== 0) {
            $this->e->xChannelVolume($this->ambCh, (float) $this->settings['volume'] * 0.6);
        }
        $this->applyRenderDist();
    }

    /** Create the visible sun/moon discs and a few drifting clouds (fog-immune). */
    private function createSky(Engine $e): void
    {
        $sky = dirname(__DIR__, 2) . '/assets/sky/';
        $fxSky = Constants::FX_FULLBRIGHT + Constants::FX_DISABLEFOG;

        $this->sunDisc = $e->xCreateSprite();
        $e->xEntityTexture($this->sunDisc, $e->xLoadTexture($sky . 'sun.png', 1 + 2 + 8));
        $e->xEntityFX($this->sunDisc, $fxSky);
        $e->xScaleSprite($this->sunDisc, 34, 34);

        $this->moonDisc = $e->xCreateSprite();
        $e->xEntityTexture($this->moonDisc, $e->xLoadTexture($sky . 'moon.png', 1 + 2 + 8));
        $e->xEntityFX($this->moonDisc, $fxSky);
        $e->xScaleSprite($this->moonDisc, 26, 26);

        // soft, airy clouds: clusters of overlapping billboard puffs
        $puffTex = $e->xLoadTexture($sky . 'puff.png', 1 + 2 + 8);
        for ($i = 0; $i < 8; $i++) {
            $pivot = $e->xCreatePivot();
            $rx = mt_rand(9, 16);   // cloud radius (blocks)
            $rz = mt_rand(6, 11);
            $puffs = mt_rand(7, 13);
            for ($p = 0; $p < $puffs; $p++) {
                $ox = (mt_rand(-100, 100) / 100.0) * $rx;
                $oz = (mt_rand(-100, 100) / 100.0) * $rz;
                $oy = (mt_rand(-100, 100) / 100.0) * 1.2;
                $size = mt_rand(7, 14);                    // puff diameter (blocks)
                $sp = $e->xCreateSprite();
                $e->xEntityTexture($sp, $puffTex);
                $e->xEntityFX($sp, $fxSky);
                $e->xEntityAlpha($sp, mt_rand(45, 75) / 100.0);
                $e->xScaleSprite($sp, $size * self::BLOCK, $size * self::BLOCK);
                $e->xEntityParent($sp, $pivot);
                $e->xPositionEntity($sp, $ox * self::BLOCK, $oy * self::BLOCK, $oz * self::BLOCK, 0);
                $this->cloudPuffs[] = $sp;
            }
            $this->clouds[] = [
                'pivot' => $pivot,
                'x'     => mt_rand(-20, 140) * self::BLOCK,
                'y'     => (self::MAX_H + mt_rand(10, 15)) * self::BLOCK,
                'z'     => mt_rand(-20, 140) * self::BLOCK,
                'sp'    => (mt_rand(2, 5) / 100.0) * self::BLOCK,
            ];
        }
    }

    /** Position sun & moon discs relative to the camera, drift the clouds. */
    private function updateSkyObjects(): void
    {
        $e = $this->e;
        $d = (int) $this->settings['renderDist'] * self::BLOCK * 0.9;
        $cxp = $e->xEntityX($this->camH, 1);
        $cyp = $e->xEntityY($this->camH, 1);
        $czp = $e->xEntityZ($this->camH, 1);

        // constant on-screen size regardless of render distance (angular size)
        $e->xScaleSprite($this->sunDisc, $d * 0.095, $d * 0.095);
        $e->xScaleSprite($this->moonDisc, $d * 0.075, $d * 0.075);

        // sun sits opposite the sun-light ray direction
        $e->xTFormVector(0, 0, 1, $this->sun, 0);
        $fx = $e->xTFormedX(); $fy = $e->xTFormedY(); $fz = $e->xTFormedZ();
        $e->xPositionEntity($this->sunDisc, $cxp - $fx * $d, $cyp - $fy * $d, $czp - $fz * $d);
        (-$fy > -0.05) ? $e->xShowEntity($this->sunDisc) : $e->xHideEntity($this->sunDisc);

        // moon sits opposite the sun (along the moon-light ray direction)
        $e->xTFormVector(0, 0, 1, $this->moon, 0);
        $mx = $e->xTFormedX(); $my = $e->xTFormedY(); $mz = $e->xTFormedZ();
        $e->xPositionEntity($this->moonDisc, $cxp - $mx * $d, $cyp - $my * $d, $czp - $mz * $d);
        (-$my > -0.05) ? $e->xShowEntity($this->moonDisc) : $e->xHideEntity($this->moonDisc);

        // clouds: tint by time of day so they aren't glaring white at night
        $v = (int) (85 + $this->dayF * 170);
        foreach ($this->cloudPuffs as $sp) {
            $e->xEntityColor($sp, $v, $v, min(255, $v + 8));
        }

        $lo = $this->px - 70 * self::BLOCK; $hi = $this->px + 70 * self::BLOCK;
        foreach ($this->clouds as &$c) {
            $c['x'] += $c['sp'];
            if ($c['x'] > $hi) { $c['x'] = $lo; }
            $e->xPositionEntity($c['pivot'], $c['x'], $c['y'], $c['z']);
        }
        unset($c);
    }

    private function updateSky(): void
    {
        $e = $this->e;

        if (!(int) $this->settings['daynight']) {
            $this->dayF = 1.0;
            $e->xCameraClsColor($this->camH, 140, 190, 235);
            $e->xCameraFogColor($this->camH, 140, 190, 235);
            $e->xRotateEntity($this->sun, 50, 30, 0);
            $e->xLightColor($this->sun, 255, 250, 235);
            $e->xLightColor($this->moon, 0, 0, 0);
            $e->xAmbientLight(120, 120, 130);
            return;
        }

        $t = getenv('CRAFT_TIME');
        $frac = ($t !== false) ? (float) $t : fmod($e->xMillisecs() / 120000.0, 1.0);
        $ang = $frac * 360.0;
        $e->xRotateEntity($this->sun, $ang, 30, 0);
        $e->xRotateEntity($this->moon, $ang + 180.0, 30, 0); // opposite the sun

        $day   = max(0.0, sin(deg2rad($ang)));   // 1 at noon, 0 at night
        $night = max(0.0, -sin(deg2rad($ang)));  // 1 at midnight, 0 at day
        $this->dayF = $day;

        // sun bright by day, moon dim-blue by night
        $e->xLightColor($this->sun, (int) (255 * $day), (int) (250 * $day), (int) (235 * $day));
        $e->xLightColor($this->moon, (int) (80 * $night), (int) (95 * $night), (int) (150 * $night));

        // sky: warm-blue day -> deep-blue night
        $r = (int) (22 + $day * 118); $g = (int) (32 + $day * 158); $b = (int) (60 + $day * 175);
        $e->xCameraClsColor($this->camH, $r, $g, $b);
        $e->xCameraFogColor($this->camH, $r, $g, $b);

        // keep night navigable (moonlit), bright at noon
        $amb = (int) (45 + $day * 80);
        $e->xAmbientLight($amb, $amb, (int) ($amb * 1.25)); // slightly blue ambient
    }

    // =================================================================== sound

    private function loadSounds(Engine $e): void
    {
        $dir = dirname(__DIR__, 2) . '/assets/sounds/';
        if (is_file($dir . 'break.wav'))   { $this->sndBreak   = $e->xLoadSound($dir . 'break.wav'); }
        if (is_file($dir . 'place.wav'))   { $this->sndPlace   = $e->xLoadSound($dir . 'place.wav'); }
        if (is_file($dir . 'step.wav'))    { $this->sndStep    = $e->xLoadSound($dir . 'step.wav'); }
        if (is_file($dir . 'ambient.wav')) {
            $this->sndAmbient = $e->xLoadSound($dir . 'ambient.wav');
            if ($this->sndAmbient !== 0) {
                $e->xLoopSound($this->sndAmbient);
                $this->ambCh = $e->xPlaySound($this->sndAmbient);
            }
        }
    }

    private function play(int $sound): void
    {
        $vol = (float) $this->settings['volume'];
        if ($sound === 0 || $vol <= 0.0) {
            return;
        }
        $this->e->xSoundVolume($sound, $vol);
        $this->e->xPlaySound($sound);
    }

    // =================================================================== setup

    private function buildTemplates(Engine $e): void
    {
        $base = dirname(__DIR__, 2) . '/assets/blocks/';
        foreach (self::TYPES as $id => [$name, $file]) {
            $cube = $e->xCreateCube();
            if ($id === 1) {
                $w = $e->xMeshWidth($cube);
                $this->scale = $w > 0.0 ? self::BLOCK / $w : 1.0;
            }
            $e->xScaleEntity($cube, $this->scale, $this->scale, $this->scale);
            $texture = $e->xLoadTexture($base . $file);
            $this->tex[$id] = $texture;
            $e->xEntityTexture($cube, $texture);
            if ($id === 11) { $e->xEntityFX($cube, 1); } // glowstone: fullbright
            if ($id === 10) { $e->xEntityAlpha($cube, 0.7); } // glass: translucent
            $e->xHideEntity($cube);
            $this->template[$id] = $cube;

            // brush per type for the merged chunk-mesh surfaces
            $b = $e->xCreateBrush();
            $e->xBrushTexture($b, $texture);
            $this->brush[$id] = $b;
        }

        // animated translucent water
        $this->waterTex = $e->xLoadAnimTexture($base . 'water.png', 1, 16, 16, 0, 32);
        $this->waterTpl = $e->xCreateCube();
        $e->xScaleEntity($this->waterTpl, $this->scale, $this->scale, $this->scale);
        $e->xEntityColor($this->waterTpl, 120, 160, 255);
        $e->xEntityAlpha($this->waterTpl, 0.7);
        $e->xEntityTexture($this->waterTpl, $this->waterTex);
        $e->xHideEntity($this->waterTpl);
    }

    private function createHand(Engine $e, int $camera): void
    {
        $this->hand = $e->xCreateCube();
        $s = $this->scale * 0.22;
        $e->xScaleEntity($this->hand, $s, $s, $s);
        $e->xEntityParent($this->hand, $camera);
        $e->xEntityFX($this->hand, 1);
        $e->xPositionEntity($this->hand, 0.95, -0.75, 2.6, 0);
        $e->xRotateEntity($this->hand, 15, 35, 0, 0);
        $this->refreshHand($e);
    }

    private function refreshHand(Engine $e): void
    {
        if ($this->hand !== 0) {
            $e->xEntityTexture($this->hand, $this->tex[$this->selectedType()]);
        }
    }

    // ============================================================ world (gen)

    /** Free all instantiated entities; keep the data model (height/edits). */
    private function clearWorld(): void
    {
        $e = $this->e;
        $this->clearMobs();
        foreach ($this->chunk as $list) {
            foreach ($list as $h) { $e->xFreeEntity($h); }
        }
        $this->chunk = $this->chunkMesh = $this->meshCk = $this->water = $this->loaded = [];
        $this->streamCX = PHP_INT_MAX;
        $this->streamCZ = PHP_INT_MAX;
    }

    private function rebuildWorld(): void
    {
        $this->clearWorld();
        $this->edits = [];
        $this->editsByChunk = [];
        $this->treeGen = [];
        $this->height = [];
        $this->generateData();
    }

    /**
     * Infinite world: nothing is precomputed. The height map, ores and trees are
     * generated procedurally per column/chunk on demand as the player explores
     * (see heightAt / groundType / loadChunk). Only a new random seed + mobs.
     */
    private function generateData(): void
    {
        $this->seed = mt_rand() / mt_getrandmax() * 1000.0;
    }

    /** Deterministically populate a chunk's trees into the edit overlay (once). */
    private function genTrees(int $cx, int $cz): void
    {
        $prob = 0.05 * (float) $this->settings['trees']; // per suitable column
        $x0 = $cx * self::CH; $z0 = $cz * self::CH;
        for ($x = $x0; $x < $x0 + self::CH; $x++) {
            for ($z = $z0; $z < $z0 + self::CH; $z++) {
                $h = $this->heightAt($x, $z);
                if ($h <= self::SEA || $h >= self::SNOW) { continue; }
                if ($this->hash3($x, 7, $z) < $prob) {
                    $this->plantTreeData($x, $h + 1, $z);
                }
            }
        }
    }

    // ------------------------------------------------------------- value noise

    private function hash2(float $x, float $z): float
    {
        $h = sin($x * 127.1 + $z * 311.7 + $this->seed) * 43758.5453;
        return $h - floor($h);
    }

    private function vnoise(float $x, float $z): float
    {
        $x0 = floor($x); $z0 = floor($z);
        $fx = $x - $x0;  $fz = $z - $z0;
        $u = $fx * $fx * (3 - 2 * $fx);
        $v = $fz * $fz * (3 - 2 * $fz);
        $a = $this->hash2($x0, $z0);       $b = $this->hash2($x0 + 1, $z0);
        $c = $this->hash2($x0, $z0 + 1);   $d = $this->hash2($x0 + 1, $z0 + 1);
        return ($a * (1 - $u) + $b * $u) * (1 - $v) + ($c * (1 - $u) + $d * $u) * $v;
    }

    private function fbm(float $x, float $z): float
    {
        $sum = 0.0; $amp = 0.5; $freq = 1.0;
        for ($o = 0; $o < 4; $o++) {
            $sum += $amp * $this->vnoise($x * $freq, $z * $freq);
            $amp *= 0.5; $freq *= 2.0;
        }
        return $sum; // 0 .. 0.9375
    }

    // ==================================================================== mobs

    private function loadMobTextures(Engine $e): void
    {
        $d = dirname(__DIR__, 2) . '/assets/mobs/';
        $this->mobTex['wool'] = $e->xLoadTexture($d . 'wool.png');
        $this->mobTex['leg']  = $e->xLoadTexture($d . 'leg.png');
        $this->mobTex['face'] = $e->xLoadTexture($d . 'face.png');
    }

    private function terrainTopY(float $wx, float $wz): float
    {
        $bx = $this->cellOf($wx); $bz = $this->cellOf($wz);
        $h = $this->heightAt($bx, $bz);
        return $h * self::BLOCK + self::BLOCK / 2;
    }

    private function isWaterAt(float $wx, float $wz): bool
    {
        $bx = $this->cellOf($wx); $bz = $this->cellOf($wz);
        return $this->heightAt($bx, $bz) < self::SEA;
    }

    /** Spawn one sheep near the player (on suitable ground), returns success. */
    private function spawnMobNear(): bool
    {
        $B = self::BLOCK;
        $reach = (int) $this->settings['renderDist'] * $B;
        for ($tries = 0; $tries < 12; $tries++) {
            $a = mt_rand(0, 359) * M_PI / 180.0;
            $dist = $reach * (0.45 + mt_rand(0, 40) / 100.0); // 0.45..0.85 of render dist
            $wx = $this->px + cos($a) * $dist;
            $wz = $this->pz + sin($a) * $dist;
            $bx = $this->cellOf($wx); $bz = $this->cellOf($wz);
            $gt = $this->groundTop($bx, $bz);
            if ($this->isWaterAt($wx, $wz) || $this->solidType($bx, $gt + 1, $bz) > 0) { continue; }
            $this->mobs[] = $this->buildSheep($wx, $wz);
            return true;
        }
        return false;
    }

    /** Keep ~cap sheep alive around the player: despawn far ones, spawn new ahead. */
    private function streamMobs(): void
    {
        $B = self::BLOCK;
        $cap = (int) $this->settings['mobs'];
        $far = (int) $this->settings['renderDist'] * $B + 20 * $B;

        foreach ($this->mobs as $i => $m) {
            if (abs($m['x'] - $this->px) > $far || abs($m['z'] - $this->pz) > $far) {
                foreach ($m['parts'] as $p) { $this->e->xFreeEntity($p); }
                $this->e->xFreeEntity($m['pivot']);
                unset($this->mobs[$i]);
            }
        }
        if (--$this->mobTimer <= 0) {
            $this->mobTimer = mt_rand(50, 130);
            if (count($this->mobs) < $cap) { $this->spawnMobNear(); }
        }
    }

    private function buildSheep(float $wx, float $wz): array
    {
        $e = $this->e; $B = self::BLOCK;
        $pivot = $e->xCreatePivot();
        $parts = [];

        $part = function (float $w, float $h, float $d, int $tex, float $ox, float $oy, float $oz) use ($e, $pivot, &$parts): void {
            $c = $e->xCreateCube();
            $e->xScaleEntity($c, $this->scale * $w, $this->scale * $h, $this->scale * $d);
            $e->xEntityTexture($c, $tex);
            $e->xEntityParent($c, $pivot);
            $e->xPositionEntity($c, $ox, $oy, $oz, 0);
            $parts[] = $c;
        };

        $wool = $this->mobTex['wool']; $leg = $this->mobTex['leg']; $face = $this->mobTex['face'];
        $part(1.1, 0.85, 0.75, $wool, 0,          0.85 * $B, 0);          // body
        $part(0.55, 0.55, 0.55, $wool, 0,         1.05 * $B, 0.62 * $B);  // head
        $part(0.35, 0.35, 0.15, $face, 0,         1.00 * $B, 0.90 * $B);  // muzzle
        foreach ([[-0.35, -0.28], [0.35, -0.28], [-0.35, 0.28], [0.35, 0.28]] as [$lx, $lz]) {
            $part(0.2, 0.55, 0.2, $leg, $lx * $B, 0.28 * $B, $lz * $B);   // legs
        }

        $e->xPositionEntity($pivot, $wx, $this->terrainTopY($wx, $wz), $wz);
        return ['pivot' => $pivot, 'parts' => $parts, 'x' => $wx, 'z' => $wz,
                'dx' => 0.0, 'dz' => 0.0, 'yaw' => 0.0, 'timer' => 0];
    }

    /** Topmost solid block cell in a column (from the data model). */
    private function groundTop(int $bx, int $bz): int
    {
        $start = $this->heightAt($bx, $bz) + 6; // account for trees / built towers
        for ($y = $start; $y >= 0; $y--) {
            if ($this->solidType($bx, $y, $bz) > 0) { return $y; }
        }
        return $this->heightAt($bx, $bz);
    }

    /**
     * Can a sheep step into this column from a ground of height $curG?
     * Blocks on: void, cliffs higher than one block, or anything occupying the
     * body space just above the surface (trees, placed blocks).
     */
    private function mobBlocked(int $bx, int $bz, int $curG): bool
    {
        $gt = $this->groundTop($bx, $bz);
        if ($gt < 0) { return true; }
        if ($gt - $curG > 1) { return true; }
        if ($this->solidType($bx, $gt + 1, $bz) > 0) { return true; }
        if ($this->solidType($bx, $gt + 2, $bz) > 0) { return true; }
        return false;
    }

    private function mobPickDir(array &$m): void
    {
        if (mt_rand(0, 3) === 0) {
            $m['dx'] = 0.0; $m['dz'] = 0.0;            // idle graze
        } else {
            $a = mt_rand(0, 359) * M_PI / 180.0;
            $m['dx'] = sin($a); $m['dz'] = cos($a);
            $m['yaw'] = $a * 180.0 / M_PI;
        }
    }

    private function mobWalkable(float $nx, float $nz, int $curG): bool
    {
        $B = self::BLOCK;
        $leash = 70 * $B; // keep sheep roaming near home
        if (abs($nx - $this->px) > $leash || abs($nz - $this->pz) > $leash) { return false; }
        if ($this->isWaterAt($nx, $nz)) { return false; }
        return !$this->mobBlocked($this->cellOf($nx), $this->cellOf($nz), $curG);
    }

    /** Try to advance, sliding around obstacles by testing nearby headings. */
    private function mobTryStep(array &$m, int $curG, float $spd): bool
    {
        $B = self::BLOCK;
        $base = atan2($m['dx'], $m['dz']);
        foreach ([0, 40, -40, 80, -80, 130, -130, 180] as $deg) {
            $a = $base + $deg * M_PI / 180.0;
            $cdx = sin($a); $cdz = cos($a);
            $nx = $m['x'] + $cdx * $spd * $B;
            $nz = $m['z'] + $cdz * $spd * $B;
            if ($this->mobWalkable($nx, $nz, $curG)) {
                $m['x'] = $nx; $m['z'] = $nz;
                $m['dx'] = $cdx; $m['dz'] = $cdz;
                $m['yaw'] = $a * 180.0 / M_PI;
                return true;
            }
        }
        return false;
    }

    private function updateMobs(): void
    {
        $e = $this->e; $B = self::BLOCK; $spd = 0.05;

        foreach ($this->mobs as &$m) {
            $curG = $this->groundTop($this->cellOf($m['x']), $this->cellOf($m['z']));

            if (--$m['timer'] <= 0) {
                $this->mobPickDir($m);
                $m['timer'] = mt_rand(80, 220);
            }

            if ($m['dx'] !== 0.0 || $m['dz'] !== 0.0) {
                if (!$this->mobTryStep($m, $curG, $spd)) {
                    // boxed in on all sides: pick a new goal shortly
                    $this->mobPickDir($m);
                    $m['timer'] = mt_rand(20, 50);
                }
            }

            $gy = $this->groundTop($this->cellOf($m['x']), $this->cellOf($m['z']));
            $y = (($gy >= 0) ? $gy : self::SEA) * $B + $B / 2;
            $e->xPositionEntity($m['pivot'], $m['x'], $y, $m['z']);
            $e->xRotateEntity($m['pivot'], 0, $m['yaw'], 0);
        }
        unset($m);
    }

    private function clearMobs(): void
    {
        foreach ($this->mobs as $m) {
            foreach ($m['parts'] as $p) { $this->e->xFreeEntity($p); }
            $this->e->xFreeEntity($m['pivot']);
        }
        $this->mobs = [];
    }

    // =============================================================== hud icons

    private function loadIcons(Engine $e): void
    {
        $base = dirname(__DIR__, 2) . '/assets/blocks/';
        foreach (self::HOTBAR as $id) {
            $img = $e->xLoadImage($base . self::TYPES[$id][1]);
            $e->xResizeImage($img, 44, 44);
            $this->icon[$id] = $img;
        }
    }

    private function exposedBottom(int $x, int $z): int
    {
        $min = $this->heightAt($x, $z);
        foreach ([[1, 0], [-1, 0], [0, 1], [0, -1]] as [$dx, $dz]) {
            $nx = $x + $dx; $nz = $z + $dz;
            $nh = $this->heightAt($nx, $nz);
            $min = min($min, $nh);
        }
        return max(0, $min);
    }

    /** Procedural surface height for ANY column (cached). Works for infinite world. */
    private function heightAt(int $x, int $z): int
    {
        if (isset($this->height[$x][$z])) { return $this->height[$x][$z]; }
        $f = $this->fbm($x * 0.08, $z * 0.08) / 0.9375;      // 0..1
        $h = (int) round((self::SEA - 1) + $f * (self::MAX_H - (self::SEA - 1)));
        $h = max(0, min(self::MAX_H, $h));
        return $this->height[$x][$z] = $h;
    }

    private function hash3(int $x, int $y, int $z): float
    {
        $h = sin($x * 127.1 + $y * 311.7 + $z * 74.7 + $this->seed) * 43758.5453;
        return $h - floor($h);
    }

    /** Ore distribution inside stone (deterministic from position). */
    private function oreAt(int $x, int $y, int $z): int
    {
        $r = $this->hash3($x, $y, $z);
        $h = $this->heightAt($x, $z);
        if ($y < $h - 6 && $r > 0.985) { return 12; } // diamond (deep, rare)
        if ($r > 0.972) { return 14; }                // iron
        if ($r > 0.945) { return 13; }                // coal
        return 3;                                     // stone
    }

    /** Natural block type at a cell (before edits). 0 = air. */
    private function groundType(int $x, int $y, int $z): int
    {
        $h = $this->heightAt($x, $z);
        if ($y > $h || $y < 0) { return 0; }
        if ($y === $h) {
            if ($h >= self::SNOW) { return 6; }   // snow cap
            if ($h <= self::SEA)  { return 9; }   // sandy beach
            return 1;                             // grass
        }
        if ($y >= $h - 2) { return 2; }           // dirt
        return $this->oreAt($x, $y, $z);          // stone / ore
    }

    private function setEdit(int $x, int $y, int $z, int $type): void
    {
        $k = "$x,$y,$z";
        $this->edits[$k] = $type;
        $ck = $this->cdiv($x) . "," . $this->cdiv($z);
        $this->editsByChunk[$ck][$k] = $type;
    }

    /** Bake a tree into the edit overlay (streamed in with its chunk). */
    private function plantTreeData(int $x, int $y, int $z): void
    {
        $trunk = mt_rand(3, 4);
        for ($i = 0; $i < $trunk; $i++) { $this->setEdit($x, $y + $i, $z, 8); }
        $top = $y + $trunk;
        for ($dy = -1; $dy <= 0; $dy++) {
            for ($dx = -2; $dx <= 2; $dx++) {
                for ($dz = -2; $dz <= 2; $dz++) {
                    if (abs($dx) === 2 && abs($dz) === 2) { continue; }
                    $this->setEdit($x + $dx, $top + $dy, $z + $dz, 7);
                }
            }
        }
        foreach ([[0, 0], [1, 0], [-1, 0], [0, 1], [0, -1]] as [$dx, $dz]) {
            $this->setEdit($x + $dx, $top + 1, $z + $dz, 7);
        }
    }

    // ============================================================ world (ops)

    private function key(int $x, int $y, int $z): string { return "$x,$y,$z"; }
    private function cdiv(int $v): int { return (int) floor($v / self::CH); }

    /** Final block type at a cell from the data model (edits over generation). 0 = air. */
    private function solidType(int $x, int $y, int $z): int
    {
        $k = "$x,$y,$z";
        if (array_key_exists($k, $this->edits)) { return $this->edits[$k]; }
        if ($y >= 0 && $y <= $this->heightAt($x, $z)) { return $this->groundType($x, $y, $z); }
        return 0;
    }

    private function spawnWater(int $ck0x, int $x, int $z, array &$list): void
    {
        $e = $this->e;
        $w = $e->xCopyEntity($this->waterTpl);
        $e->xPositionEntity($w, $x * self::BLOCK, self::SEA * self::BLOCK, $z * self::BLOCK);
        $this->water[$w] = true;
        $list[] = $w;
    }

    // ------------------------------------------------ merged chunk meshing

    /** Cube face corner offsets (unit) + neighbour direction, per face. */
    private const FACES = [
        [[1, 0, 0],  [[1, -1, 1], [1, -1, -1], [1, 1, -1], [1, 1, 1]]],   // +X
        [[-1, 0, 0], [[-1, -1, -1], [-1, -1, 1], [-1, 1, 1], [-1, 1, -1]]], // -X
        [[0, 1, 0],  [[-1, 1, 1], [1, 1, 1], [1, 1, -1], [-1, 1, -1]]],   // +Y
        [[0, -1, 0], [[-1, -1, -1], [1, -1, -1], [1, -1, 1], [-1, -1, 1]]], // -Y
        [[0, 0, 1],  [[-1, -1, 1], [1, -1, 1], [1, 1, 1], [-1, 1, 1]]],   // +Z
        [[0, 0, -1], [[1, -1, -1], [-1, -1, -1], [-1, 1, -1], [1, 1, -1]]], // -Z
    ];

    /** Add the exposed faces of one solid cell to the per-type surfaces. */
    private function emitCell(int $mesh, array &$surf, int $x, int $y, int $z, int $type): void
    {
        $e = $this->e; $B = self::BLOCK; $h = $B / 2;
        $cx = $x * $B; $cy = $y * $B; $cz = $z * $B;
        foreach (self::FACES as [$n, $corners]) {
            if ($this->solidType($x + $n[0], $y + $n[1], $z + $n[2]) > 0) { continue; } // hidden face
            if (!isset($surf[$type])) {
                $surf[$type] = $e->xCreateSurface($mesh, $this->brush[$type]);
            }
            $s = $surf[$type];
            $v = [];
            $uv = [[0, 0], [1, 0], [1, 1], [0, 1]];
            foreach ($corners as $i => $c) {
                $v[] = $e->xAddVertex($s, $cx + $c[0] * $h, $cy + $c[1] * $h, $cz + $c[2] * $h, $uv[$i][0], $uv[$i][1]);
            }
            $e->xAddTriangle($s, $v[0], $v[1], $v[2]);
            $e->xAddTriangle($s, $v[0], $v[2], $v[3]);
        }
    }

    /** Build (or rebuild) one chunk as a single merged, face-culled mesh. */
    private function buildChunkMesh(int $cx, int $cz): void
    {
        $e = $this->e;
        $ck = "$cx,$cz";

        // free previous entities of this chunk (rebuild case)
        foreach ($this->chunk[$ck] ?? [] as $h) {
            unset($this->meshCk[$h], $this->water[$h]);
            $e->xFreeEntity($h);
        }
        $this->chunk[$ck] = [];

        if (!isset($this->treeGen[$ck])) { $this->treeGen[$ck] = true; $this->genTrees($cx, $cz); }

        $mesh = $e->xCreateMesh();
        $surf = [];
        $x0 = $cx * self::CH; $z0 = $cz * self::CH;
        $waterOn = (int) $this->settings['water'];
        $list = [];

        for ($x = $x0; $x < $x0 + self::CH; $x++) {
            for ($z = $z0; $z < $z0 + self::CH; $z++) {
                $top = $this->heightAt($x, $z);
                $yMax = $top;
                // include any stacked edits above the terrain (trees / towers)
                for ($y = 0; $y <= $yMax; $y++) {
                    $t = $this->solidType($x, $y, $z);
                    if ($t > 0) { $this->emitCell($mesh, $surf, $x, $y, $z, $t); }
                }
                if ($waterOn && $top < self::SEA) { $this->spawnWater($cx, $x, $z, $list); }
            }
        }
        // edits above terrain top (trees/placed) within this chunk
        foreach ($this->editsByChunk[$ck] ?? [] as $k => $t) {
            if ($t <= 0) { continue; }
            [$x, $y, $z] = array_map('intval', explode(',', $k));
            if ($y > $this->heightAt($x, $z)) { $this->emitCell($mesh, $surf, $x, $y, $z, $t); }
        }

        $e->xUpdateNormals($mesh);
        $e->xEntityPickMode($mesh, 2);

        $this->chunkMesh[$ck] = $mesh;
        $this->meshCk[$mesh] = $ck;
        $this->chunk[$ck] = array_merge([$mesh], $list);
    }

    private function loadChunk(int $cx, int $cz): void
    {
        $ck = "$cx,$cz";
        if (isset($this->loaded[$ck])) { return; }
        $this->loaded[$ck] = true;
        $this->buildChunkMesh($cx, $cz);
    }

    private function rebuildChunk(int $cx, int $cz): void
    {
        if (isset($this->loaded["$cx,$cz"])) { $this->buildChunkMesh($cx, $cz); }
    }

    private function unloadChunk(int $cx, int $cz): void
    {
        $ck = "$cx,$cz";
        if (!isset($this->loaded[$ck])) { return; }
        $e = $this->e;
        foreach ($this->chunk[$ck] ?? [] as $h) {
            unset($this->meshCk[$h], $this->water[$h]);
            $e->xFreeEntity($h);
        }
        unset($this->chunk[$ck], $this->chunkMesh[$ck], $this->loaded[$ck]);
    }

    /** Load chunks within render distance of ($wx,$wz); unload the rest. */
    private function updateStreaming(float $wx, float $wz): void
    {
        $pcx = $this->cdiv($this->cellOf($wx));
        $pcz = $this->cdiv($this->cellOf($wz));
        if ($pcx === $this->streamCX && $pcz === $this->streamCZ) { return; }
        $this->streamCX = $pcx; $this->streamCZ = $pcz;

        $r = (int) ceil(((int) $this->settings['renderDist']) / self::CH);
        $u = $r + 1;

        for ($cx = $pcx - $r; $cx <= $pcx + $r; $cx++) {
            for ($cz = $pcz - $r; $cz <= $pcz + $r; $cz++) {
                if (!isset($this->loaded["$cx,$cz"])) { $this->loadChunk($cx, $cz); }
            }
        }
        foreach (array_keys($this->loaded) as $ck) {
            [$cx, $cz] = explode(',', $ck);
            if (abs((int) $cx - $pcx) > $u || abs((int) $cz - $pcz) > $u) {
                $this->unloadChunk((int) $cx, (int) $cz);
            }
        }
    }

    private function applyRenderDist(): void
    {
        $d = (int) $this->settings['renderDist'] * self::BLOCK;
        $this->e->xCameraRange($this->camH, 0.2, $d * 1.3);
        $this->e->xCameraFogRange($this->camH, $d * 0.55, $d * 0.95);
        $this->streamCX = PHP_INT_MAX; // force a streaming refresh
        $this->streamCZ = PHP_INT_MAX;
    }

    // =================================================================== bloom

    private function setupBloom(Engine $e): void
    {
        $fx = $this->config->media('Shaders/Bloom.fx');
        if (!is_file($fx)) { $this->bloomOK = false; return; }
        $this->bloomFX = $e->xLoadFXFile($fx);
        if (!$e->xValidateEffectTechnique($this->bloomFX, 'Diffuse')) {
            $this->bloomOK = false;   // GPU can't run it -> silently skip
            return;
        }
        $w = (int) $this->settings['width'];
        $h = (int) $this->settings['height'];
        $this->bloomPoly = $e->xCreatePostEffectPoly($this->camH, 1);
        $this->bloomTexS = $e->xCreateTexture(256, 256);
        $this->bloomTexF = $e->xCreateTexture($w, $h);
        $e->xSetEntityEffect($this->bloomPoly, $this->bloomFX);
        $e->xSetEffectTechnique($this->bloomPoly, 'Diffuse');
        $e->xSetEffectMatrixSemantic($this->bloomPoly, 'MatWorldViewProj', Constants::WORLDVIEWPROJ);
        $e->xSetEffectTexture($this->bloomPoly, 'tDiffuse', $this->bloomTexS);
        $e->xSetEffectTexture($this->bloomPoly, 'tEmissive', $this->bloomTexF);
        $this->bloomOK = true;
    }

    /** Bright-pass + separable blur bloom, run as a post effect over the frame. */
    private function renderBloom(): void
    {
        if (!$this->bloomOK || !(int) $this->settings['bloom']) { return; }
        $e = $this->e;
        $w = (int) $this->settings['width'];
        $h = (int) $this->settings['height'];
        $e->xStretchBackBuffer($this->bloomTexS, 0, 0, 256, 256, 0);
        $e->xStretchBackBuffer($this->bloomTexF, 0, 0, $w, $h, 0);
        $e->xSetEffectTechnique($this->bloomPoly, 'Diffuse');  $e->xRenderPostEffect($this->bloomPoly);
        $e->xStretchBackBuffer($this->bloomTexS, 0, 0, 256, 256, 0);
        $e->xSetEffectTechnique($this->bloomPoly, 'DiffuseH'); $e->xRenderPostEffect($this->bloomPoly);
        $e->xStretchBackBuffer($this->bloomTexS, 0, 0, 256, 256, 0);
        $e->xSetEffectTechnique($this->bloomPoly, 'DiffuseV'); $e->xRenderPostEffect($this->bloomPoly);
    }

    // ================================================================ god rays

    private function setupGodRays(Engine $e): void
    {
        $fx = dirname(__DIR__, 2) . '/assets/shaders/GodRays.fx';
        if (!is_file($fx)) { $this->godOK = false; return; }
        $this->godFX = $e->xLoadFXFile($fx);
        if (!$e->xValidateEffectTechnique($this->godFX, 'Rays')) {
            $this->godOK = false;   // GPU/shader model unsupported -> skip
            return;
        }
        $w = (int) $this->settings['width'];
        $h = (int) $this->settings['height'];
        $this->godPoly = $e->xCreatePostEffectPoly($this->camH, 1);
        $this->godTex  = $e->xCreateTexture($w, $h);
        $e->xSetEntityEffect($this->godPoly, $this->godFX);
        $e->xSetEffectTechnique($this->godPoly, 'Rays');
        $e->xSetEffectMatrixSemantic($this->godPoly, 'MatWorldViewProj', Constants::WORLDVIEWPROJ);
        $e->xSetEffectTexture($this->godPoly, 'tScene', $this->godTex);
        $e->xSetEffectFloat($this->godPoly, 'Density', 0.88);
        $e->xSetEffectFloat($this->godPoly, 'Decay', 0.965);
        $e->xSetEffectFloat($this->godPoly, 'Weight', 0.45);
        $e->xSetEffectFloat($this->godPoly, 'Threshold', 0.8);
        $this->godOK = true;
    }

    /** Radial light shafts from the sun, when it is on screen. */
    private function renderGodRays(): void
    {
        if (!$this->godOK || !(int) $this->settings['godrays'] || $this->dayF <= 0.05) {
            return;
        }
        $e = $this->e;
        $w = (int) $this->settings['width'];
        $h = (int) $this->settings['height'];

        // is the sun in front of the camera?
        $sx = $e->xEntityX($this->sunDisc, 1);
        $sy = $e->xEntityY($this->sunDisc, 1);
        $sz = $e->xEntityZ($this->sunDisc, 1);
        $e->xTFormVector(0, 0, 1, $this->camH, 0);
        $fwx = $e->xTFormedX(); $fwy = $e->xTFormedY(); $fwz = $e->xTFormedZ();
        $tx = $sx - $e->xEntityX($this->camH, 1);
        $ty = $sy - $e->xEntityY($this->camH, 1);
        $tz = $sz - $e->xEntityZ($this->camH, 1);
        if ($fwx * $tx + $fwy * $ty + $fwz * $tz <= 0.0) { return; } // sun behind camera

        $e->xCameraProject($this->camH, $sx, $sy, $sz);
        $u = $e->xProjectedX() / $w;
        $v = $e->xProjectedY() / $h;
        if ($u < -0.6 || $u > 1.6 || $v < -0.6 || $v > 1.6) { return; } // far off-screen

        $e->xSetEffectVector($this->godPoly, 'SunUV', $u, $v, 0, 0);
        $e->xSetEffectVector($this->godPoly, 'RayColor', 1.0, 0.92, 0.65, 0);

        $e->xStretchBackBuffer($this->godTex, 0, 0, $w, $h, 0);
        $e->xSetEffectTechnique($this->godPoly, 'Rays');
        $e->xRenderPostEffect($this->godPoly);
    }

    /** Rebuild the chunk containing (x,z) plus horizontal neighbours (border faces). */
    private function rebuildAround(int $x, int $z): void
    {
        $done = [];
        foreach ([[0, 0], [1, 0], [-1, 0], [0, 1], [0, -1]] as [$dx, $dz]) {
            $cx = $this->cdiv($x + $dx); $cz = $this->cdiv($z + $dz);
            $ck = "$cx,$cz";
            if (!isset($done[$ck])) { $done[$ck] = true; $this->rebuildChunk($cx, $cz); }
        }
    }

    private function destroyAt(Engine $e, int $x, int $y, int $z): void
    {
        if ($this->solidType($x, $y, $z) <= 0) { return; }
        $this->setEdit($x, $y, $z, 0); // record removal in the data model
        $this->play($this->sndBreak);
        $this->rebuildAround($x, $z);
    }

    private function placeAt(Engine $e, int $x, int $y, int $z, int $type): void
    {
        if ($y < 0 || $y > self::Y_MAX) { return; }
        if ($this->solidType($x, $y, $z) > 0) { return; }
        $this->setEdit($x, $y, $z, $type);
        $this->play($this->sndPlace);
        $this->rebuildAround($x, $z);
    }

    private function faceOffset(Engine $e): array
    {
        $nx = $e->xPickedNX(); $ny = $e->xPickedNY(); $nz = $e->xPickedNZ();
        $ax = abs($nx); $ay = abs($ny); $az = abs($nz);
        if ($ax >= $ay && $ax >= $az) { return [$nx < 0 ? -1 : 1, 0, 0]; }
        if ($ay >= $az)               { return [0, $ny < 0 ? -1 : 1, 0]; }
        return [0, 0, $nz < 0 ? -1 : 1];
    }

    // ============================================================ save / load

    private function worldFile(): string { return dirname(__DIR__, 2) . '/craft-world.json'; }

    private function saveWorld(): void
    {
        // infinite world: only the seed + player edits + which chunks have trees.
        // Terrain/ores regenerate procedurally from the seed.
        $data = ['seed' => $this->seed, 'edits' => $this->edits, 'treeGen' => array_keys($this->treeGen)];
        $ok = @file_put_contents($this->worldFile(), json_encode($data)) !== false;
        $this->status = $ok ? 'World saved.' : 'Save failed.';
    }

    private function loadWorld(): void
    {
        $f = $this->worldFile();
        if (!is_file($f) || ($d = json_decode((string) file_get_contents($f), true)) === null) {
            $this->status = 'No saved world.';
            return;
        }
        $this->clearWorld();
        $this->seed = (float) ($d['seed'] ?? 0);
        $this->height = [];
        $this->edits = [];
        $this->editsByChunk = [];
        $this->treeGen = [];
        foreach (($d['treeGen'] ?? []) as $ck) { $this->treeGen[(string) $ck] = true; }
        foreach (($d['edits'] ?? []) as $k => $type) {
            [$x, $y, $z] = array_map('intval', explode(',', (string) $k));
            $this->setEdit($x, $y, $z, (int) $type);
        }
        $this->status = 'World loaded.'; // chunks stream in around the player on Play
    }

    // ==================================================================== menus

    private function mainMenu(): string
    {
        $items   = ['Play', 'New World', 'Save World', 'Load World', 'Settings', 'Quit'];
        $actions = ['play', 'new', 'save', 'load', 'settings', 'quit'];
        $sel = 0; $e = $this->e;
        $this->streamCX = PHP_INT_MAX;
        $this->updateStreaming($this->originX, $this->originZ); // stream the area around the map centre
        $shot = getenv('CRAFT_MENUSHOT'); $sf = 0;

        while (true) {
            if ($this->closeRequested()) { $this->quit = true; return 'quit'; }
            if ($e->xKeyHit(Constants::KEY_UP))   { $sel = ($sel + count($items) - 1) % count($items); }
            if ($e->xKeyHit(Constants::KEY_DOWN)) { $sel = ($sel + 1) % count($items); }
            if ($e->xKeyHit(Constants::KEY_ESCAPE)) { return 'quit'; }
            if ($e->xKeyHit(Constants::KEY_RETURN)) { return $actions[$sel]; }

            $this->orbitBackdrop();
            $w = $e->xGraphicsWidth();
            $e->xColor(255, 255, 255);
            $e->xText($w / 2, 150, 'C R A F T', 1);
            $e->xColor(200, 220, 255);
            $e->xText($w / 2, 180, 'a voxel world for Xors3d (PHP / FFI)', 1);
            foreach ($items as $i => $label) {
                $e->xColor(...($i === $sel ? [255, 240, 120] : [210, 210, 210]));
                $e->xText($w / 2, 250 + $i * 32, $i === $sel ? "> $label <" : $label, 1);
            }
            if ($this->status !== '') {
                $e->xColor(120, 255, 160);
                $e->xText($w / 2, 250 + count($items) * 32 + 10, $this->status, 1);
            }
            $e->xColor(150, 150, 150);
            $e->xText($w / 2, $e->xGraphicsHeight() - 40, 'Arrows: move    Enter: select    Esc: quit', 1);
            if ($shot && ++$sf > 40) { $e->xSaveBuffer($e->xBackBuffer(), $shot); $this->quit = true; return 'quit'; }
            $e->xFlip();
        }
    }

    private function settingsMenu(): void
    {
        $opts = self::OPTIONS; $sel = 0; $e = $this->e;
        $shot = getenv('CRAFT_SETSHOT'); $sf = 0;

        while (true) {
            if ($this->closeRequested()) { $this->quit = true; return; }
            if ($e->xKeyHit(Constants::KEY_ESCAPE)) { $this->saveSettings(); return; }
            if ($e->xKeyHit(Constants::KEY_UP))   { $sel = ($sel + count($opts) - 1) % count($opts); }
            if ($e->xKeyHit(Constants::KEY_DOWN)) { $sel = ($sel + 1) % count($opts); }
            if ($e->xKeyHit(Constants::KEY_LEFT))  { $this->adjust($opts[$sel], -1); }
            if ($e->xKeyHit(Constants::KEY_RIGHT)) { $this->adjust($opts[$sel], +1); }

            $this->orbitBackdrop();
            $w = $e->xGraphicsWidth();
            $e->xColor(255, 255, 255);
            $e->xText($w / 2, 70, 'S E T T I N G S', 1);
            foreach ($opts as $i => $opt) {
                $note = isset($opt['note']) ? "  ({$opt['note']})" : '';
                $line = sprintf('%-18s  < %s >%s', $opt['label'], $this->valueText($opt), $note);
                $e->xColor(...($i === $sel ? [255, 240, 120] : [210, 210, 210]));
                $e->xText($w / 2, 130 + $i * 32, $line, 1);
            }
            $e->xColor(150, 150, 150);
            $e->xText($w / 2, $e->xGraphicsHeight() - 40, 'Up/Down: choose    Left/Right: change    Esc: back (saves)', 1);
            if ($shot && ++$sf > 40) { $e->xSaveBuffer($e->xBackBuffer(), $shot); $this->quit = true; return; }
            $e->xFlip();
        }
    }

    private function valueText(array $opt): string
    {
        $k = $opt['key'];
        return match ($opt['type']) {
            'bool'  => ((int) $this->settings[$k] ? 'On' : 'Off'),
            'int'   => (string) (int) $this->settings[$k],
            'float' => number_format((float) $this->settings[$k], 2),
            'res'   => (int) $this->settings['width'] . 'x' . (int) $this->settings['height'],
            default => (string) $this->settings[$k],
        };
    }

    private function adjust(array $opt, int $dir): void
    {
        $k = $opt['key'];
        switch ($opt['type']) {
            case 'bool':
                $this->settings[$k] = (int) !((int) $this->settings[$k]);
                break;
            case 'int':
                $this->settings[$k] = (int) max($opt['min'], min($opt['max'], (int) $this->settings[$k] + $dir * $opt['step']));
                break;
            case 'float':
                $v = (float) $this->settings[$k] + $dir * $opt['step'];
                $this->settings[$k] = round(max($opt['min'], min($opt['max'], $v)), 2);
                break;
            case 'res':
                $cur = 0;
                foreach (self::RESOLUTIONS as $i => [$rw, $rh]) {
                    if ((int) $this->settings['width'] === $rw && (int) $this->settings['height'] === $rh) { $cur = $i; }
                }
                $cur = ($cur + $dir + count(self::RESOLUTIONS)) % count(self::RESOLUTIONS);
                [$this->settings['width'], $this->settings['height']] = self::RESOLUTIONS[$cur];
                break;
        }
        $this->applySettings();
        $this->saveSettings();
    }

    private function orbitBackdrop(): void
    {
        $e = $this->e;
        $mid = $this->originX;
        $t = $e->xMillisecs() / 4000.0;
        $r = (int) $this->settings["renderDist"] * self::BLOCK * 0.8;
        $e->xPositionEntity($this->pivot, $mid, self::MAX_H * self::BLOCK, $mid);
        $e->xPositionEntity($this->camH, $mid + cos($t) * $r, (self::MAX_H + 6) * self::BLOCK, $mid + sin($t) * $r);
        $e->xPointEntity($this->camH, $this->pivot);
        $this->updateSky();
        $this->updateSkyObjects();
        $this->animateWater();
        $this->streamMobs();
        $this->updateMobs();
        $e->xRenderWorld();
    }

    // ================================================================ gameplay

    /** True if a solid (non-water) block occupies this voxel cell. */
    private function solidCell(int $bx, int $by, int $bz): bool
    {
        return $this->solidType($bx, $by, $bz) > 0;
    }

    private function cellOf(float $w): int
    {
        return (int) floor(($w + self::BLOCK / 2) / self::BLOCK);
    }

    private function move(): void
    {
        $e = $this->e;
        $fly = $this->fly;

        // direction from camera transform (so it follows where you look)
        $e->xTFormVector(0, 0, 1, $this->camH, 0);
        $fwx = $e->xTFormedX(); $fwy = $e->xTFormedY(); $fwz = $e->xTFormedZ();
        $e->xTFormVector(1, 0, 0, $this->camH, 0);
        $rgx = $e->xTFormedX(); $rgy = $e->xTFormedY(); $rgz = $e->xTFormedZ();

        if (!$fly) { // project onto XZ for walking
            $fl = hypot($fwx, $fwz) ?: 1.0; $fwx /= $fl; $fwz /= $fl; $fwy = 0.0;
            $rl = hypot($rgx, $rgz) ?: 1.0; $rgx /= $rl; $rgz /= $rl; $rgy = 0.0;
        }

        $spd = $fly ? self::SPD_FLY : self::SPD_WALK;
        $mx = $my = $mz = 0.0;
        if ($e->xKeyDown(Constants::KEY_W)) { $mx += $fwx; $my += $fwy; $mz += $fwz; }
        if ($e->xKeyDown(Constants::KEY_S)) { $mx -= $fwx; $my -= $fwy; $mz -= $fwz; }
        if ($e->xKeyDown(Constants::KEY_D)) { $mx += $rgx; $my += $rgy; $mz += $rgz; }
        if ($e->xKeyDown(Constants::KEY_A)) { $mx -= $rgx; $my -= $rgy; $mz -= $rgz; }
        $ml = hypot(hypot($mx, $my), $mz);
        if ($ml > 0.0) { $mx = $mx / $ml * $spd; $my = $my / $ml * $spd; $mz = $mz / $ml * $spd; }

        $moving = $ml > 0.0;

        if ($fly) {
            $this->px += $mx; $this->py += $my; $this->pz += $mz;
            if ($e->xKeyDown(Constants::KEY_SPACE))  { $this->py += $spd; }
            if ($e->xKeyDown(Constants::KEY_LSHIFT)) { $this->py -= $spd; }
        } else {
            $this->moveAxisX($mx);
            $this->moveAxisZ($mz);
            $this->applyGravity();
            if ($this->onGround && $e->xKeyHit(Constants::KEY_SPACE)) { $this->vy = self::JUMP; }
            // footsteps
            if ($moving && $this->onGround) {
                $now = $e->xMillisecs();
                if ($now - $this->lastStep > 340) { $this->play($this->sndStep); $this->lastStep = $now; }
            }
            if ($this->py < -30.0) { $this->spawnPlayer(); } // fell out of the world
        }

        $e->xPositionEntity($this->camH, $this->px, $this->py + self::EYE, $this->pz);
    }

    private function blockedAt(float $x, float $z): bool
    {
        $bx = $this->cellOf($x); $bz = $this->cellOf($z);
        $c1 = $this->cellOf($this->py + 0.2);
        $c2 = $this->cellOf($this->py + self::PH - 0.2);
        return $this->solidCell($bx, $c1, $bz) || $this->solidCell($bx, $c2, $bz);
    }

    private function moveAxisX(float $mx): void
    {
        if ($mx === 0.0) { return; }
        $tx = $this->px + $mx + ($mx > 0 ? self::HW : -self::HW);
        if (!$this->blockedAt($tx, $this->pz)) { $this->px += $mx; }
    }

    private function moveAxisZ(float $mz): void
    {
        if ($mz === 0.0) { return; }
        $tz = $this->pz + $mz + ($mz > 0 ? self::HW : -self::HW);
        if (!$this->blockedAt($this->px, $tz)) { $this->pz += $mz; }
    }

    private function applyGravity(): void
    {
        $this->vy -= self::G;
        $ny = $this->py + $this->vy;
        $bx = $this->cellOf($this->px); $bz = $this->cellOf($this->pz);

        if ($this->vy <= 0.0) {
            $fc = $this->cellOf($ny);
            if ($this->solidCell($bx, $fc, $bz)) {
                $this->py = $fc * self::BLOCK + self::BLOCK / 2 + 0.02;
                $this->vy = 0.0;
                $this->onGround = true;
                return;
            }
            $this->onGround = false;
        } else {
            $hc = $this->cellOf($this->py + self::PH + $this->vy);
            if ($this->solidCell($bx, $hc, $bz)) { $this->vy = 0.0; return; }
        }
        $this->py = $ny;
    }

    private function animateWater(): void
    {
        if ($this->waterTex === 0 || $this->water === []) { return; }
        $frame = (int) ($this->e->xMillisecs() / 90) % 32;
        foreach (array_keys($this->water) as $w) {
            $this->e->xEntityTexture($w, $this->waterTex, $frame);
        }
    }

    private function gameLoop(int $max): void
    {
        $e = $this->e; $h = $this->camH; $frame = 0;

        while (true) {
            if ($this->closeRequested()) { $this->quit = true; return; }
            if ($max === 0 && $e->xKeyHit(Constants::KEY_ESCAPE)) { return; }

            if ($e->xKeyHit(Constants::KEY_F)) { $this->fly = !$this->fly; $this->vy = 0.0; }

            $this->cam->lookOnly();
            $this->move();
            $this->updateStreaming($this->px, $this->pz);
            $this->animateWater();
            $this->streamMobs();
            $this->updateMobs();

            // block selection: number keys 1-9 + mouse wheel
            for ($n = 1; $n <= count(self::HOTBAR); $n++) {
                if ($e->xKeyHit(Constants::KEY_1 + ($n - 1))) { $this->slot = $n - 1; $this->refreshHand($e); }
            }
            $wheel = $e->xMouseZSpeed();
            if ($wheel !== 0) {
                $c = count(self::HOTBAR);
                $this->slot = (($this->slot - ($wheel > 0 ? 1 : -1)) % $c + $c) % $c;
                $this->refreshHand($e);
            }
            $e->xTurnEntity($this->hand, 0, 1.5, 0);
            $this->updateSky();
            $this->updateSkyObjects();

            $cx = (int) ($e->xGraphicsWidth() / 2);
            $cy = (int) ($e->xGraphicsHeight() / 2);
            $e->xCameraPick($h, $cx, $cy);
            $picked = $e->xPickedEntity();
            $hasTarget = $picked !== 0 && isset($this->meshCk[$picked]);

            if ($hasTarget) {
                // pick point + face normal -> the block cell just inside / outside the face
                $px = $e->xPickedX(); $py = $e->xPickedY(); $pz = $e->xPickedZ();
                [$dx, $dy, $dz] = $this->faceOffset($e);
                $q = self::BLOCK * 0.25;
                if ($e->xMouseHit(1)) {
                    $bx = $this->cellOf($px - $dx * $q);
                    $by = $this->cellOf($py - $dy * $q);
                    $bz = $this->cellOf($pz - $dz * $q);
                    $this->destroyAt($e, $bx, $by, $bz);
                } elseif ($e->xMouseHit(2) || $e->xMouseHit(3)) {
                    $bx = $this->cellOf($px + $dx * $q);
                    $by = $this->cellOf($py + $dy * $q);
                    $bz = $this->cellOf($pz + $dz * $q);
                    $this->placeAt($e, $bx, $by, $bz, $this->selectedType());
                }
            }

            if ($max > 0 && getenv('CRAFT_LOOKUP')) { $e->xRotateEntity($h, -40, 40, 0); }

            $e->xRenderWorld();
            $this->renderGodRays();
            $this->renderBloom();
            $this->drawHud($e, $hasTarget);

            if ($max > 0 && $frame + 1 >= $max && ($shot = getenv('CRAFT_SHOT'))) {
                $e->xSaveBuffer($e->xBackBuffer(), $shot);
            }
            $e->xFlip();
            if ($max > 0 && ++$frame >= $max) { return; }
        }
    }

    private function drawHud(Engine $e, bool $hasTarget): void
    {
        $w = $e->xGraphicsWidth();
        $cx = (int) ($w / 2);
        $cy = (int) ($e->xGraphicsHeight() / 2);

        // crosshair (two lines)
        $e->xColor(255, 255, 255);
        $e->xLine($cx - 9, $cy, $cx + 9, $cy);
        $e->xLine($cx, $cy - 9, $cx, $cy + 9);

        $e->xColor(255, 255, 0);
        $e->xText(10, 10, 'FPS: ' . $e->xGetFPS());
        $e->xColor(220, 220, 220);
        $e->xText(10, 30, 'Chunks: ' . count($this->chunkMesh) . '   Sheep: ' . count($this->mobs));
        $e->xText(10, 50, 'Mode: ' . ($this->fly ? 'Fly (F)' : 'Walk (F)'));
        $e->xText(10, 70, $hasTarget ? 'LMB destroy / RMB place' : 'no target');
        $e->xText(10, 90, 'Esc: menu');

        // visual hotbar: block icons with a selection frame
        $slots = count(self::HOTBAR);
        $cell = 52; $pad = 4; $iw = 44;
        $barW = $slots * $cell;
        $x0 = $cx - (int) ($barW / 2);
        $y0 = $e->xGraphicsHeight() - $cell - 8;
        foreach (self::HOTBAR as $i => $id) {
            $sx = $x0 + $i * $cell;
            $e->xColor(20, 20, 20);
            $e->xRect($sx, $y0, $cell - 2, $cell - 2, 1);             // slot background
            $e->xDrawImage($this->icon[$id], $sx + $pad, $y0 + $pad);  // block icon
            if ($i === $this->slot) {
                $e->xColor(255, 255, 255);
                $e->xRect($sx - 1, $y0 - 1, $cell, $cell, 0);          // selection frame
            }
            $e->xColor(200, 200, 200);
            $e->xText($sx + 4, $y0 + 2, (string) ($i + 1));            // slot number
        }
        // selected block name
        $e->xColor(255, 255, 255);
        $e->xText($cx, $y0 - 18, self::TYPES[$this->selectedType()][0], 1);
    }
}
