<?php

declare(strict_types=1);

namespace Xors3D\Controllers;

use Xors3D\Controllers\Craft\Assets;
use Xors3D\Controllers\Craft\Bed;
use Xors3D\Controllers\Craft\Chunks;
use Xors3D\Controllers\Craft\Effects;
use Xors3D\Controllers\Craft\Furnace;
use Xors3D\Controllers\Craft\Inventory;
use Xors3D\Controllers\Craft\Minimap;
use Xors3D\Controllers\Craft\Mobs;
use Xors3D\Controllers\Craft\Player;
use Xors3D\Controllers\Craft\Sky;
use Xors3D\Controllers\Craft\Storage;
use Xors3D\Controllers\Craft\Structures;
use Xors3D\Controllers\Craft\Survival;
use Xors3D\Controllers\Craft\TerrainGen;
use Xors3D\Controllers\Craft\Ui;
use Xors3D\Controllers\Craft\Weather;
use Xors3D\Controllers\Craft\World;
use Xors3D\Core\Controller;
use Xors3D\Ffi\Constants;
use Xors3D\Ffi\Engine;
use Xors3D\Scene\MouseLookCamera;

/**
 * "Craft" - a Minecraft-like voxel game for Xors3d (PHP / FFI).
 *
 * Menu:      Play / New World / Save World / Load World / Settings / Quit
 * Settings:  sensitivity, invert-Y, FOV, fog, day/night, sound volume,
 *            resolution, vsync, world size, tree density, water
 * Game:      WASD + mouse, F = fly/walk toggle, SPACE jump (walk) or up (fly),
 *            SHIFT down (fly), LMB destroy, RMB place, 1-9 / mouse wheel = block,
 *            Esc = menu.
 *
 * Features: procedural world + biomes (grass/sand beach/snow caps), trees,
 * animated translucent water, walking with gravity + voxel collision, a held
 * block ("hand"), save/load, and synthesized sound (break/place/steps/ambient).
 *
 * Textures are real 16x16 Minecraft tiles in assets/blocks/; sounds are
 * generated by bin/gen_sounds.php into assets/sounds/.
 */
final class MinecraftController extends Controller
{
    use TerrainGen; // procedural terrain/noise/caves/ores (src/Controllers/Craft/)
    use Mobs;       // passive animals + world-query helpers (src/Controllers/Craft/)
    use Weather;    // precipitation, overcast, snow settle, puddles (src/Controllers/Craft/)
    use Inventory;  // item counts, drops, crafting recipes + menu (src/Controllers/Craft/)
    use Chunks;     // greedy meshing + budgeted chunk streaming + fog (src/Controllers/Craft/)
    use Structures; // spawn plaza, buildings, trees, procedural landmarks (src/Controllers/Craft/)
    use Sky;        // sun/moon, clouds, day/night sky + light (src/Controllers/Craft/)
    use Player;     // WASD/fly movement, collision, gravity, step-up (src/Controllers/Craft/)
    use Effects;    // break particles, torch point-lights, bloom + god-rays (src/Controllers/Craft/)
    use Ui;         // settings, menus, backdrop, HUD (src/Controllers/Craft/)
    use Assets;     // sounds, block templates + brushes, hand (src/Controllers/Craft/)
    use World;      // edits, solidType, (re)gen, break/place, doors, save/load (src/Controllers/Craft/)
    use Survival;   // health, fall damage, drowning, hearts HUD (src/Controllers/Craft/)
    use Storage;    // chest inventories + transfer menu (src/Controllers/Craft/)
    use Bed;        // sleep (B) at night near a bed to skip to morning (src/Controllers/Craft/)
    use Furnace;    // smelting menu (sand->glass etc) with fuel (src/Controllers/Craft/)
    use Minimap;    // top-right surface minimap (src/Controllers/Craft/)

    public const TITLE = 'Minecraft-like game (menu, walk, water, sound)';

    private const MAX_H = 22;
    private const SNOW  = 16;
    private const SEA   = 4;
    private const Y_MAX = 140;  // mesh height cap (chunks only mesh up to their real
                                // content height, so this only affects tall structures)
    private const BLOCK = 2.0;
    private const CH    = 8;      // chunk size (columns) for render-distance culling

    // player physics (world units)
    private const G     = 0.03;
    private const JUMP  = 0.55;
    private const PH    = 3.0;   // player height
    private const EYE   = 2.6;   // eye height above feet
    private const HW    = 0.55;  // player half width
    private const SPD_WALK = 0.20;
    private const SPD_FLY  = 0.55;

    private const RESOLUTIONS = [
        [800, 600], [1024, 768], [1280, 720], [1366, 768], [1600, 900], [1920, 1080],
    ];

    /** Block type id => [name, texture file]. */
    private const TYPES = [
        1  => ['Grass',     'grass.png'],
        2  => ['Dirt',      'dirt.png'],
        3  => ['Stone',     'stone.png'],
        4  => ['Brick',     'brick.png'],
        5  => ['Wood',      'wood.png'],
        6  => ['Snow',      'snow.png'],
        7  => ['Leaves',    'leaves.png'],
        8  => ['Log',       'log.png'],
        9  => ['Sand',      'sand.png'],
        10 => ['Glass',     'glass.png'],
        11 => ['Glowstone', 'glowstone.png'],
        12 => ['Diamond',   'diamond_ore.png'],
        13 => ['Coal',      'coal.png'],
        14 => ['Iron',      'iron.png'],
        15 => ['Cobblestone',   'cobblestone.png'],
        16 => ['Stone Bricks',  'stonebrick.png'],
        17 => ['Oak Planks',    'oakplanks.png'],
        18 => ['Dark Planks',   'darkplanks.png'],
        19 => ['Bookshelf',     'bookshelf.png'],
        20 => ['Red Wool',      'redwool.png'],
        21 => ['White Wool',    'whitewool.png'],
        22 => ['Chiseled Stone', 'chiseledstone.png'],
        23 => ['Door',          'door.png'],
        24 => ['Chest',         'chest.png'],
        25 => ['Furnace',       'furnace.png'],
    ];

    private const DOOR = 23;
    private const CHEST = 24;
    private const FURNACE = 25;

    /** Current hotbar (block type per slot). Keys 1-9 pick the first nine; wheel cycles all. */
    private array $hotbar = [1, 2, 3, 5, 15, 16, 17, 10, 23, 24, 25, 11, 18, 19, 20, 21, 22];

    /** @var array<string,array<int,int>> chest cell "x,y,z" => its stored inventory */
    private array $chests = [];

    /** @var array<int,int> inventory: block type id => count held */
    private array $inv = [];

    /**
     * Crafting recipes: 'in' = [typeId => count] consumed, 'out' = [typeId, count] produced.
     * A simplified survival tree (log->planks, cobble->bricks, sand->glass, etc.).
     */
    private const RECIPES = [
        ['in' => [8 => 1],            'out' => [17, 4]],  // 1 Log        -> 4 Oak Planks
        ['in' => [17 => 6],           'out' => [23, 1]],  // 6 Oak Planks -> 1 Door
        ['in' => [17 => 6],           'out' => [19, 1]],  // 6 Oak Planks -> 1 Bookshelf
        ['in' => [17 => 4],           'out' => [18, 4]],  // 4 Oak Planks -> 4 Dark Planks
        ['in' => [15 => 4],           'out' => [16, 4]],  // 4 Cobblestone-> 4 Stone Bricks
        ['in' => [16 => 4],           'out' => [22, 1]],  // 4 Stone Brick-> 1 Chiseled Stone
        ['in' => [9 => 1],            'out' => [10, 1]],  // 1 Sand       -> 1 Glass
        ['in' => [4 => 4],            'out' => [15, 4]],  // 4 Brick      -> 4 Cobblestone
        ['in' => [13 => 4],           'out' => [11, 1]],  // 4 Coal       -> 1 Glowstone (lamp)
        ['in' => [2 => 4],            'out' => [4, 1]],   // 4 Dirt       -> 1 Brick
        ['in' => [17 => 8],           'out' => [24, 1]],  // 8 Oak Planks -> 1 Chest
        ['in' => [15 => 8],           'out' => [25, 1]],  // 8 Cobblestone-> 1 Furnace
    ];

    /**
     * Smelting recipes (furnace): input type => output type. Each smelt burns one fuel.
     */
    private const SMELT = [
        9  => 10,  // Sand        -> Glass
        15 => 3,   // Cobblestone -> Stone
        8  => 13,  // Log         -> Coal (charcoal)
        2  => 4,   // Dirt        -> Brick (fired)
    ];

    /** Block types that can be burned as furnace fuel. */
    private const FUELS = [13, 8, 5, 17, 18]; // coal, log, wood, oak/dark planks

    /** @var array<string,int|float> */
    private array $settings = [
        'width' => 1024, 'height' => 768, 'vsync' => 1,
        'sensitivity' => 0.5, 'invertY' => 0, 'fov' => 1.0,
        'fog' => 1, 'daynight' => 1, 'volume' => 0.8, 'renderDist' => 48,
        'bloom' => 0, 'godrays' => 1, 'weather' => 1, 'survival' => 1, 'minimap' => 0,
        'worldSize' => 96, 'trees' => 1.0, 'water' => 1, 'mobs' => 8,
    ];

    private const OPTIONS = [
        ['key' => 'sensitivity', 'label' => 'Mouse sensitivity', 'type' => 'float', 'min' => 0.1, 'max' => 2.0, 'step' => 0.05],
        ['key' => 'invertY',     'label' => 'Invert mouse Y',    'type' => 'bool'],
        ['key' => 'fov',         'label' => 'Field of view',     'type' => 'float', 'min' => 0.6, 'max' => 1.6, 'step' => 0.1],
        ['key' => 'fog',         'label' => 'Fog',               'type' => 'bool'],
        ['key' => 'daynight',    'label' => 'Day/night cycle',   'type' => 'bool'],
        ['key' => 'weather',     'label' => 'Weather (rain/snow)', 'type' => 'bool'],
        ['key' => 'survival',    'label' => 'Survival (health)',  'type' => 'bool'],
        ['key' => 'minimap',     'label' => 'Minimap',           'type' => 'bool'],
        ['key' => 'bloom',       'label' => 'Bloom (shader)',    'type' => 'bool'],
        ['key' => 'godrays',     'label' => 'Sun rays (shader)', 'type' => 'bool'],
        ['key' => 'volume',      'label' => 'Sound volume',      'type' => 'float', 'min' => 0.0, 'max' => 1.0, 'step' => 0.1],
        ['key' => 'renderDist',  'label' => 'Render distance',   'type' => 'int',  'min' => 16, 'max' => 96, 'step' => 8],
        ['key' => 'resolution',  'label' => 'Resolution',        'type' => 'res',  'note' => 'restart'],
        ['key' => 'vsync',       'label' => 'VSync',             'type' => 'bool', 'note' => 'restart'],
        ['key' => 'trees',       'label' => 'Tree density',      'type' => 'float', 'min' => 0.0, 'max' => 3.0, 'step' => 0.5, 'note' => 'new world'],
        ['key' => 'water',       'label' => 'Water',             'type' => 'bool', 'note' => 'new world'],
        ['key' => 'mobs',        'label' => 'Animal count',      'type' => 'int',  'min' => 0, 'max' => 24, 'step' => 2, 'note' => 'new world'],
    ];

    private Engine $e;
    private MouseLookCamera $cam;
    private int $camH = 0;
    private int $pivot = 0;
    private int $sun = 0;
    private string $status = '';
    private bool $quit = false;

    private int $wsize = 20;
    private float $scale = 1.0;
    private int $slot = 0;           // hotbar index
    private int $hand = 0;
    private bool $fly = false;

    // player state (feet position, world units)
    private float $px = 0.0;
    private float $py = 0.0;
    private float $pz = 0.0;
    private float $vy = 0.0;
    private bool $onGround = false;

    // survival state (health / fall damage / drowning)
    private float $hp = 20.0;      // 0..20 (10 hearts)
    private float $breath = 10.0;  // air left underwater
    private float $airMaxY = 0.0;  // peak height reached while airborne (for fall damage)
    private bool $wasGround = true;
    private bool $fallGrace = true; // skip fall damage on the initial spawn drop
    private float $timeShift = 0.0; // day-cycle offset (sleeping in a bed skips to morning)
    /** @var int[] cached minimap cell colours (packed rgb), resampled a few times/sec */
    private array $mmCells = [];
    private int $mmMs = 0;
    private int $backdropFrame = 0; // deterministic menu/settings backdrop orbit counter
    private int $lastStep = 0;
    private int $mobTimer = 0;
    private float $dt = 1.0;     // frame time factor (1.0 == 60 FPS) for FPS-independent speed
    private int $lastMs = 0;
    private float $acc = 0.0;   // fixed-timestep accumulator (in 60 FPS-frame units)

    /** @var array<int,int> */ private array $template = [];
    /** @var array<int,int> */ private array $tex = [];
    private int $waterTpl = 0;
    private int $waterTex = 0;
    /** @var array<int,bool> water entity handle => true */ private array $water = [];
    /** @var array<int,array<int,int>> */ private array $height = [];
    /** @var array<int,array<int,float>> biome value cache (0..1) */ private array $biome = [];

    // streaming chunks + edit overlay (generative world)
    /** @var array<string,int[]> "cx,cz" => entity handles (mesh + water) */ private array $chunk = [];
    /** @var array<string,bool> loaded chunk keys */ private array $loaded = [];
    /** @var array<string,int> "x,y,z" => type (0 = removed): tree + player edits over generated world */ private array $edits = [];
    /** @var array<string,array<string,int>> chunk key => its edits */ private array $editsByChunk = [];
    /** @var array<string,bool> door cell "x,y,z" => open? */ private array $doorOpen = [];
    /** @var array<string,array{0:int,1:int,2:int}> glowstone cells "x,y,z" => [x,y,z] (light sources) */
    private array $lightCells = [];
    /** @var array<string,float> per-chunk-build baked block-light field "x,y,z" => 0..1 */
    private array $blockLite = [];
    /** @var int[] pool of dynamic point-light handles bound to the nearest torches */
    private array $pointLights = [];
    /** @var array<int,?string> pool index => bound light-source cell key (stable binding) */
    private array $lightBind = [];
    /** @var array<string,bool> chunks whose trees have been generated */ private array $treeGen = [];
    /** @var array<string,bool> chunk keys touched by the tree gen currently running */ private array $treeSpill = [];
    private bool $trackSpill = false;
    /** @var array<int,int> block type => brush (textured) for chunk meshes */ private array $brush = [];
    /** @var array<string,int> chunk key => merged mesh handle */ private array $chunkMesh = [];
    /** @var array<int,string> mesh handle => chunk key (for picking) */ private array $meshCk = [];
    /** @var array<string,int[]> unloaded-but-kept chunk entity lists (hidden), LRU-ordered for reuse on backtrack */
    private array $chunkCache = [];
    private const CHUNK_CACHE_MAX = 192; // keep this many recently-seen chunks meshed but hidden
    private int $streamCX = PHP_INT_MAX;
    private int $streamCZ = PHP_INT_MAX;
    /** @var array<string,bool> chunks wanted but not yet built (budgeted load queue) */
    private array $loadQ = [];
    /** @var array<string,bool> loaded chunks pending a rebuild (e.g. snow settle/melt) */
    private array $rebuildQ = [];
    private float $originX = 0.0;   // player home (world units), for mobs/backdrop
    private float $originZ = 0.0;

    private float $seed = 0.0;
    private int $sunDisc = 0;
    private int $moonDisc = 0;
    private int $moon = 0;   // night directional light
    private float $dayF = 1.0; // 0 night .. 1 noon (for tinting sky objects)
    /** @var array<int,array<string,mixed>> drifting cloud slabs */
    private array $clouds = [];
    /** @var int[] all cloud puff sprite handles (for day/night tinting) */
    private array $cloudPuffs = [];

    // weather: a pool of falling billboard sprites (rain streaks / snow flakes)
    private int $rainTex = 0;
    private int $snowTex = 0;
    /** @var array<int,array<string,float|int>> particle pool: [sp, x, y, z, vy, sway] */
    private array $drops = [];
    private int $weather = 0;      // 0 = clear, 1 = rain, 2 = snow
    private float $weatherTimer = 0.0; // frames until the next weather roll
    private float $wetness = 0.0;   // 0..1 eased overcast amount for sky darkening
    private bool $snowOn = false;   // snow is lying on the ground (top faces rendered white)
    private float $snowBuild = 0.0; // frames of snow before it covers the ground
    private int $puddleTpl = 0;     // thin water-slab template for rain puddles
    /** @var array<int,array<string,int|float>> puddle pool: [ent, x, z, placed] */
    private array $puddles = [];
    /** @var array<int,array<string,int|float>> block-break particle bursts */
    private array $particles = [];
    /** @var array<int,int> hotbar type id => 2D icon image handle */
    private array $icon = [];
    /** @var array<string,int> mob part textures */
    private array $mobTex = [];
    /** @var array<int,array<string,mixed>> active sheep mobs */
    private array $mobs = [];

    // bloom post-effect (shader)
    private int $bloomPoly = 0;
    private int $bloomTexS = 0;
    private int $bloomTexF = 0;
    private int $bloomFX = 0;
    private bool $bloomOK = false;

    // god-rays post-effect (shader)
    private int $godPoly = 0;
    private int $godTex = 0;
    private int $godFX = 0;
    private bool $godOK = false;

    // sounds
    private int $sndBreak = 0;
    private int $sndPlace = 0;
    private int $sndStep = 0;
    private int $sndAmbient = 0;
    private int $ambCh = 0;

    // ===================================================================== run

    public function index(int|string $maxFrames = 0): int
    {
        $max = (int) $maxFrames;
        $e = $this->e = $this->engine;

        $this->loadSettings();

        $e->xKey($this->config->firstKey());
        $e->xSetAntiAliasType($e->xGetMaxAntiAlias());
        $e->xAppTitle('Craft - Xors3d voxel game (PHP)');
        $e->xGraphics3D((int) $this->settings['width'], (int) $this->settings['height'], 32, 0, (int) $this->settings['vsync']);
        $e->xAntiAlias(1);
        $e->xSetTextureFiltering(Constants::TF_POINT);
        $e->xHidePointer();

        $this->cam = new MouseLookCamera($e);
        $this->camH = $this->cam->handle();
        $e->xCameraClsColor($this->camH, 115, 185, 245);
        $e->xCameraRange($this->camH, 0.2, 600);
        $e->xCameraFogColor($this->camH, 115, 185, 245);
        $e->xCameraFogRange($this->camH, 60, 260);

        $this->sun = $e->xCreateLight(Constants::LIGHT_DIRECTIONAL);
        $e->xRotateEntity($this->sun, 50, 30, 0);
        $this->moon = $e->xCreateLight(Constants::LIGHT_DIRECTIONAL);
        $e->xRotateEntity($this->moon, 230, 30, 0);
        $e->xLightColor($this->moon, 0, 0, 0);
        $e->xAmbientLight(120, 120, 130);

        // pool of point lights bound to the nearest torches/glowstone (2 directional +
        // 6 point = the 8-light fixed-function limit). Stable binding + distance fade
        // so lights don't pop as you move.
        for ($i = 0; $i < 6; $i++) {
            $l = $e->xCreateLight(Constants::LIGHT_POINT);
            $e->xLightColor($l, 255, 205, 130);          // warm torchlight
            $e->xLightRange($l, 11.0 * self::BLOCK);
            $e->xHideEntity($l);
            $this->pointLights[] = $l;
            $this->lightBind[$i] = null;
        }
        $e->xLoadFont('Arial', 14);

        $this->buildTemplates($e);
        $this->loadIcons($e);
        $this->loadMobTextures($e);
        $this->createSky($e);
        $this->createHand($e, $this->camH);
        $this->pivot = $e->xCreatePivot();
        $this->loadSounds($e);
        $this->setupBloom($e);
        $this->setupGodRays($e);
        $this->applySettings();
        $this->rebuildWorld();

        if ($max > 0) {
            $this->spawnPlayer();
            $this->gameLoop($max);
            $e->xReleaseGraphics();
            return 0;
        }

        if (getenv('CRAFT_SETSHOT')) { $this->settingsMenu(); $e->xReleaseGraphics(); return 0; }

        while (!$this->quit) {
            $action = $this->mainMenu();
            if ($this->quit || $action === 'quit') {
                break;
            }
            if ($action === 'save')     { $this->saveWorld(); continue; }
            if ($action === 'load')     { $this->loadWorld(); continue; }
            if ($action === 'settings') { $this->settingsMenu(); continue; }
            if ($action === 'new')      { $this->rebuildWorld(); $this->status = 'New world generated.'; }
            $this->spawnPlayer();
            $this->gameLoop(0);
        }

        $e->xReleaseGraphics();
        return 0;
    }

    // ================================================================= helpers

    private function closeRequested(): bool
    {
        return (bool) $this->e->xWinMessage('WM_CLOSE');
    }

    private function selectedType(): int
    {
        return $this->hotbar[$this->slot];
    }

    private function spawnPlayer(): void
    {
        $this->px = $this->originX;
        $this->pz = $this->originZ;
        $this->py = (self::MAX_H + 6) * self::BLOCK;
        $this->vy = 0.0;
        $this->onGround = false;
        $this->cam->reset();
        $this->e->xPositionEntity($this->camH, $this->px, $this->py + self::EYE, $this->pz);
        $this->streamCX = PHP_INT_MAX;              // force streaming refresh
        $this->updateStreaming($this->px, $this->pz); // queue the world around spawn
        // Pre-build the whole visible area during the (already-present) spawn load. The
        // spawn plaza is full of heavy chunks - the floating island makes very tall meshes
        // and the lamps/castle bake a lot of block-light - so building them here (a one-time
        // load pause) avoids multi-hundred-ms hitches when you fly around them afterwards.
        // Fresh terrain you explore later still streams in per-frame (time-budgeted).
        $this->flushStreaming();
        $this->clearMobs();                        // sheep re-stream around the new spot
        $this->mobTimer = 0;
        $seed = min(4, (int) $this->settings['mobs']);
        for ($i = 0; $i < $seed; $i++) { $this->spawnMobNear(); } // a few right away
        $this->resetVitals();
    }

    // ================================================================ settings




    // ==================================================================== menus


    private function gameLoop(int $max): void
    {
        $e = $this->e; $h = $this->camH; $frame = 0;
        $this->lastMs = PHP_INT_MIN;
        // Cinematic capture mode (for README media): drive the camera on a scripted orbit
        // over the village, hide the HUD, and optionally save a clean frame sequence for a GIF.
        $cine = (bool) getenv('CRAFT_CINE');
        $seq  = getenv('CRAFT_SHOTSEQ') ?: '';
        if (!$cine) { $e->xShowEntity($this->hand); } // the menu backdrop hides it; restore for play

        while (true) {
            if ($this->closeRequested()) { $this->quit = true; return; }
            if ($max === 0 && $e->xKeyHit(Constants::KEY_ESCAPE)) { return; }

            // Frame time in "60 FPS-frame" units. xMillisecs() is a SIGNED 32-bit ms
            // counter and goes negative after ~24.8 days of uptime, so never test it with
            // "> 0"; use a sentinel for the first frame and treat a negative/huge delta
            // (wrap or hitch) as one frame.
            $now = $e->xMillisecs();
            $frameMs = ($this->lastMs === PHP_INT_MIN) ? 16 : ($now - $this->lastMs);
            $this->lastMs = $now;
            if ($frameMs < 0 || $frameMs > 250) { $frameMs = 16; }
            $frameDt = min(3.0, $frameMs / 16.6667);

            if ($e->xKeyHit(Constants::KEY_F)) { $this->fly = !$this->fly; $this->vy = 0.0; }

            $this->cam->lookOnly();

            // Fixed-timestep physics: run movement/collision/gravity in constant 1/60 s
            // steps regardless of render FPS. This keeps speed AND collision behaviour
            // identical at 60 or 440+ FPS (collision look-ahead no longer scales with the
            // frame's step size). Leftover time carries to the next frame; capped to avoid
            // a spiral of death after a big hitch.
            $this->acc += $frameDt;
            $this->dt = 1.0;
            $steps = 0;
            while (!$cine && $this->acc >= 1.0 && $steps < 5) {
                $this->move();
                $this->acc -= 1.0;
                $steps++;
            }
            if ($cine) { $this->acc = 0.0; $this->cineCamera($frame, $max); }
            $this->dt = $frameDt; // restore real frame dt for per-frame visuals below

            $this->updateStreaming($this->px, $this->pz);
            if ($cine) { $this->flushStreaming(); } // fully build each frame -> no pop-in in the capture
            else { $this->processStreaming(2, 2); } // budgeted (count + time): a few chunks/frame, no hitches
            $this->animateWater();
            $this->streamMobs();
            $this->updateMobs();

            // block selection: number keys 1-9 (first nine) + mouse wheel (all)
            for ($n = 1; $n <= min(9, count($this->hotbar)); $n++) {
                if ($e->xKeyHit(Constants::KEY_1 + ($n - 1))) { $this->slot = $n - 1; $this->refreshHand($e); }
            }
            $wheel = $e->xMouseZSpeed();
            if ($wheel !== 0) {
                $c = count($this->hotbar);
                $this->slot = (($this->slot - ($wheel > 0 ? 1 : -1)) % $c + $c) % $c;
                $this->refreshHand($e);
            }
            $e->xTurnEntity($this->hand, 0, 1.5 * $this->dt, 0);
            $this->updateSky();
            $this->updateSkyObjects();
            $this->updateWeather();
            $this->updatePuddles();
            $this->updateParticles();
            $this->updatePointLights();
            $this->updateSurvival();

            $cx = (int) ($e->xGraphicsWidth() / 2);
            $cy = (int) ($e->xGraphicsHeight() / 2);
            $e->xCameraPick($h, $cx, $cy);
            $picked = $e->xPickedEntity();
            $hasTarget = $picked !== 0 && isset($this->meshCk[$picked]);

            if ($hasTarget) {
                // pick point + face normal -> the block cell just inside / outside the face
                $px = $e->xPickedX(); $py = $e->xPickedY(); $pz = $e->xPickedZ();
                [$dx, $dy, $dz] = $this->faceOffset($e);
                $q = self::BLOCK * 0.25;
                if ($e->xMouseHit(1)) {
                    $bx = $this->cellOf($px - $dx * $q);
                    $by = $this->cellOf($py - $dy * $q);
                    $bz = $this->cellOf($pz - $dz * $q);
                    $this->destroyAt($e, $bx, $by, $bz);
                } elseif ($e->xMouseHit(2) || $e->xMouseHit(3)) {
                    $bx = $this->cellOf($px + $dx * $q);
                    $by = $this->cellOf($py + $dy * $q);
                    $bz = $this->cellOf($pz + $dz * $q);
                    $this->placeAt($e, $bx, $by, $bz, $this->selectedType());
                } elseif ($e->xKeyHit(Constants::KEY_E)) {
                    // E: open a chest, otherwise open/close a door
                    $bx = $this->cellOf($px - $dx * $q);
                    $by = $this->cellOf($py - $dy * $q);
                    $bz = $this->cellOf($pz - $dz * $q);
                    $bt = $this->solidType($bx, $by, $bz);
                    if ($bt === self::CHEST)        { $this->openChest($bx, $by, $bz); }
                    elseif ($bt === self::FURNACE)  { $this->openFurnace(); }
                    else                            { $this->toggleDoor($bx, $by, $bz); }
                }
            }

            // C opens the crafting / block menu (assigns a block to the active slot)
            if ($e->xKeyHit(Constants::KEY_C)) { $this->craftMenu(); }
            if ($e->xKeyHit(Constants::KEY_B)) { $this->trySleep(); }
            if ($e->xKeyHit(Constants::KEY_M)) { $this->settings['minimap'] = (int) $this->settings['minimap'] ? 0 : 1; }

            if ($max > 0 && getenv('CRAFT_LOOKUP')) { $e->xRotateEntity($h, -40, 40, 0); }

            $e->xRenderWorld();
            $this->renderGodRays();
            $this->renderBloom();
            if (!$cine) {                         // clean, HUD-less frames for cinematic capture
                $this->drawHud($e, $hasTarget);
                $this->drawVitals($e);
                $this->drawMinimap($e);
            }

            if ($max > 0 && $frame + 1 >= $max && ($shot = getenv('CRAFT_SHOT'))) {
                $e->xSaveBuffer($e->xBackBuffer(), $shot);
            }
            if ($seq !== '') { $e->xSaveBuffer($e->xBackBuffer(), sprintf('%s_%03d.bmp', $seq, $frame)); }
            $e->xFlip();
            if ($max > 0 && ++$frame >= $max) { return; }
        }
    }


}
