<?php

declare(strict_types=1);

namespace Xors3D\Controllers;

use Xors3D\Controllers\Craft\Chunks;
use Xors3D\Controllers\Craft\Inventory;
use Xors3D\Controllers\Craft\Mobs;
use Xors3D\Controllers\Craft\TerrainGen;
use Xors3D\Controllers\Craft\Weather;
use Xors3D\Core\Controller;
use Xors3D\Ffi\Constants;
use Xors3D\Ffi\Engine;
use Xors3D\Scene\MouseLookCamera;

/**
 * "Craft" - a Minecraft-like voxel game for Xors3d (PHP / FFI).
 *
 * Menu:      Play / New World / Save World / Load World / Settings / Quit
 * Settings:  sensitivity, invert-Y, FOV, fog, day/night, sound volume,
 *            resolution, vsync, world size, tree density, water
 * Game:      WASD + mouse, F = fly/walk toggle, SPACE jump (walk) or up (fly),
 *            SHIFT down (fly), LMB destroy, RMB place, 1-9 / mouse wheel = block,
 *            Esc = menu.
 *
 * Features: procedural world + biomes (grass/sand beach/snow caps), trees,
 * animated translucent water, walking with gravity + voxel collision, a held
 * block ("hand"), save/load, and synthesized sound (break/place/steps/ambient).
 *
 * Textures are real 16x16 Minecraft tiles in assets/blocks/; sounds are
 * generated by bin/gen_sounds.php into assets/sounds/.
 */
final class MinecraftController extends Controller
{
    use TerrainGen; // procedural terrain/noise/caves/ores (src/Controllers/Craft/)
    use Mobs;       // passive animals + world-query helpers (src/Controllers/Craft/)
    use Weather;    // precipitation, overcast, snow settle, puddles (src/Controllers/Craft/)
    use Inventory;  // item counts, drops, crafting recipes + menu (src/Controllers/Craft/)
    use Chunks;     // greedy meshing + budgeted chunk streaming + fog (src/Controllers/Craft/)

    public const TITLE = 'Minecraft-like game (menu, walk, water, sound)';

    private const MAX_H = 22;
    private const SNOW  = 16;
    private const SEA   = 4;
    private const Y_MAX = 140;  // mesh height cap (chunks only mesh up to their real
                                // content height, so this only affects tall structures)
    private const BLOCK = 2.0;
    private const CH    = 8;      // chunk size (columns) for render-distance culling

    // player physics (world units)
    private const G     = 0.03;
    private const JUMP  = 0.55;
    private const PH    = 3.0;   // player height
    private const EYE   = 2.6;   // eye height above feet
    private const HW    = 0.55;  // player half width
    private const SPD_WALK = 0.20;
    private const SPD_FLY  = 0.55;

    private const RESOLUTIONS = [
        [800, 600], [1024, 768], [1280, 720], [1366, 768], [1600, 900], [1920, 1080],
    ];

    /** Block type id => [name, texture file]. */
    private const TYPES = [
        1  => ['Grass',     'grass.png'],
        2  => ['Dirt',      'dirt.png'],
        3  => ['Stone',     'stone.png'],
        4  => ['Brick',     'brick.png'],
        5  => ['Wood',      'wood.png'],
        6  => ['Snow',      'snow.png'],
        7  => ['Leaves',    'leaves.png'],
        8  => ['Log',       'log.png'],
        9  => ['Sand',      'sand.png'],
        10 => ['Glass',     'glass.png'],
        11 => ['Glowstone', 'glowstone.png'],
        12 => ['Diamond',   'diamond_ore.png'],
        13 => ['Coal',      'coal.png'],
        14 => ['Iron',      'iron.png'],
        15 => ['Cobblestone',   'cobblestone.png'],
        16 => ['Stone Bricks',  'stonebrick.png'],
        17 => ['Oak Planks',    'oakplanks.png'],
        18 => ['Dark Planks',   'darkplanks.png'],
        19 => ['Bookshelf',     'bookshelf.png'],
        20 => ['Red Wool',      'redwool.png'],
        21 => ['White Wool',    'whitewool.png'],
        22 => ['Chiseled Stone', 'chiseledstone.png'],
        23 => ['Door',          'door.png'],
    ];

    private const DOOR = 23;

    /** Current hotbar (block type per slot). Keys 1-9 pick the first nine; wheel cycles all. */
    private array $hotbar = [1, 2, 3, 5, 15, 16, 17, 10, 23, 11, 18, 19, 20, 21, 22];

    /** @var array<int,int> inventory: block type id => count held */
    private array $inv = [];

    /**
     * Crafting recipes: 'in' = [typeId => count] consumed, 'out' = [typeId, count] produced.
     * A simplified survival tree (log->planks, cobble->bricks, sand->glass, etc.).
     */
    private const RECIPES = [
        ['in' => [8 => 1],            'out' => [17, 4]],  // 1 Log        -> 4 Oak Planks
        ['in' => [17 => 6],           'out' => [23, 1]],  // 6 Oak Planks -> 1 Door
        ['in' => [17 => 6],           'out' => [19, 1]],  // 6 Oak Planks -> 1 Bookshelf
        ['in' => [17 => 4],           'out' => [18, 4]],  // 4 Oak Planks -> 4 Dark Planks
        ['in' => [15 => 4],           'out' => [16, 4]],  // 4 Cobblestone-> 4 Stone Bricks
        ['in' => [16 => 4],           'out' => [22, 1]],  // 4 Stone Brick-> 1 Chiseled Stone
        ['in' => [9 => 1],            'out' => [10, 1]],  // 1 Sand       -> 1 Glass
        ['in' => [4 => 4],            'out' => [15, 4]],  // 4 Brick      -> 4 Cobblestone
        ['in' => [13 => 4],           'out' => [11, 1]],  // 4 Coal       -> 1 Glowstone (lamp)
        ['in' => [2 => 4],            'out' => [4, 1]],   // 4 Dirt       -> 1 Brick
    ];

    /** @var array<string,int|float> */
    private array $settings = [
        'width' => 1024, 'height' => 768, 'vsync' => 1,
        'sensitivity' => 0.5, 'invertY' => 0, 'fov' => 1.0,
        'fog' => 1, 'daynight' => 1, 'volume' => 0.8, 'renderDist' => 48,
        'bloom' => 0, 'godrays' => 1, 'weather' => 1,
        'worldSize' => 96, 'trees' => 1.0, 'water' => 1, 'mobs' => 8,
    ];

    private const OPTIONS = [
        ['key' => 'sensitivity', 'label' => 'Mouse sensitivity', 'type' => 'float', 'min' => 0.1, 'max' => 2.0, 'step' => 0.05],
        ['key' => 'invertY',     'label' => 'Invert mouse Y',    'type' => 'bool'],
        ['key' => 'fov',         'label' => 'Field of view',     'type' => 'float', 'min' => 0.6, 'max' => 1.6, 'step' => 0.1],
        ['key' => 'fog',         'label' => 'Fog',               'type' => 'bool'],
        ['key' => 'daynight',    'label' => 'Day/night cycle',   'type' => 'bool'],
        ['key' => 'weather',     'label' => 'Weather (rain/snow)', 'type' => 'bool'],
        ['key' => 'bloom',       'label' => 'Bloom (shader)',    'type' => 'bool'],
        ['key' => 'godrays',     'label' => 'Sun rays (shader)', 'type' => 'bool'],
        ['key' => 'volume',      'label' => 'Sound volume',      'type' => 'float', 'min' => 0.0, 'max' => 1.0, 'step' => 0.1],
        ['key' => 'renderDist',  'label' => 'Render distance',   'type' => 'int',  'min' => 16, 'max' => 96, 'step' => 8],
        ['key' => 'resolution',  'label' => 'Resolution',        'type' => 'res',  'note' => 'restart'],
        ['key' => 'vsync',       'label' => 'VSync',             'type' => 'bool', 'note' => 'restart'],
        ['key' => 'trees',       'label' => 'Tree density',      'type' => 'float', 'min' => 0.0, 'max' => 3.0, 'step' => 0.5, 'note' => 'new world'],
        ['key' => 'water',       'label' => 'Water',             'type' => 'bool', 'note' => 'new world'],
        ['key' => 'mobs',        'label' => 'Animal count',      'type' => 'int',  'min' => 0, 'max' => 24, 'step' => 2, 'note' => 'new world'],
    ];

    private Engine $e;
    private MouseLookCamera $cam;
    private int $camH = 0;
    private int $pivot = 0;
    private int $sun = 0;
    private string $status = '';
    private bool $quit = false;

    private int $wsize = 20;
    private float $scale = 1.0;
    private int $slot = 0;           // hotbar index
    private int $hand = 0;
    private bool $fly = false;

    // player state (feet position, world units)
    private float $px = 0.0;
    private float $py = 0.0;
    private float $pz = 0.0;
    private float $vy = 0.0;
    private bool $onGround = false;
    private int $lastStep = 0;
    private int $mobTimer = 0;
    private float $dt = 1.0;     // frame time factor (1.0 == 60 FPS) for FPS-independent speed
    private int $lastMs = 0;
    private float $acc = 0.0;   // fixed-timestep accumulator (in 60 FPS-frame units)

    /** @var array<int,int> */ private array $template = [];
    /** @var array<int,int> */ private array $tex = [];
    private int $waterTpl = 0;
    private int $waterTex = 0;
    /** @var array<int,bool> water entity handle => true */ private array $water = [];
    /** @var array<int,array<int,int>> */ private array $height = [];
    /** @var array<int,array<int,float>> biome value cache (0..1) */ private array $biome = [];

    // streaming chunks + edit overlay (generative world)
    /** @var array<string,int[]> "cx,cz" => entity handles (mesh + water) */ private array $chunk = [];
    /** @var array<string,bool> loaded chunk keys */ private array $loaded = [];
    /** @var array<string,int> "x,y,z" => type (0 = removed): tree + player edits over generated world */ private array $edits = [];
    /** @var array<string,array<string,int>> chunk key => its edits */ private array $editsByChunk = [];
    /** @var array<string,bool> door cell "x,y,z" => open? */ private array $doorOpen = [];
    /** @var array<string,array{0:int,1:int,2:int}> glowstone cells "x,y,z" => [x,y,z] (light sources) */
    private array $lightCells = [];
    /** @var int[] pool of dynamic point-light handles reassigned to the nearest torches */
    private array $pointLights = [];
    /** @var array<string,bool> chunks whose trees have been generated */ private array $treeGen = [];
    /** @var array<string,bool> chunk keys touched by the tree gen currently running */ private array $treeSpill = [];
    private bool $trackSpill = false;
    /** @var array<int,int> block type => brush (textured) for chunk meshes */ private array $brush = [];
    /** @var array<string,int> chunk key => merged mesh handle */ private array $chunkMesh = [];
    /** @var array<int,string> mesh handle => chunk key (for picking) */ private array $meshCk = [];
    private int $streamCX = PHP_INT_MAX;
    private int $streamCZ = PHP_INT_MAX;
    /** @var array<string,bool> chunks wanted but not yet built (budgeted load queue) */
    private array $loadQ = [];
    /** @var array<string,bool> loaded chunks pending a rebuild (e.g. snow settle/melt) */
    private array $rebuildQ = [];
    private float $originX = 0.0;   // player home (world units), for mobs/backdrop
    private float $originZ = 0.0;

    private float $seed = 0.0;
    private int $sunDisc = 0;
    private int $moonDisc = 0;
    private int $moon = 0;   // night directional light
    private float $dayF = 1.0; // 0 night .. 1 noon (for tinting sky objects)
    /** @var array<int,array<string,mixed>> drifting cloud slabs */
    private array $clouds = [];
    /** @var int[] all cloud puff sprite handles (for day/night tinting) */
    private array $cloudPuffs = [];

    // weather: a pool of falling billboard sprites (rain streaks / snow flakes)
    private int $rainTex = 0;
    private int $snowTex = 0;
    /** @var array<int,array<string,float|int>> particle pool: [sp, x, y, z, vy, sway] */
    private array $drops = [];
    private int $weather = 0;      // 0 = clear, 1 = rain, 2 = snow
    private float $weatherTimer = 0.0; // frames until the next weather roll
    private float $wetness = 0.0;   // 0..1 eased overcast amount for sky darkening
    private bool $snowOn = false;   // snow is lying on the ground (top faces rendered white)
    private float $snowBuild = 0.0; // frames of snow before it covers the ground
    private int $puddleTpl = 0;     // thin water-slab template for rain puddles
    /** @var array<int,array<string,int|float>> puddle pool: [ent, x, z, placed] */
    private array $puddles = [];
    /** @var array<int,array<string,int|float>> block-break particle bursts */
    private array $particles = [];
    /** @var array<int,int> hotbar type id => 2D icon image handle */
    private array $icon = [];
    /** @var array<string,int> mob part textures */
    private array $mobTex = [];
    /** @var array<int,array<string,mixed>> active sheep mobs */
    private array $mobs = [];

    // bloom post-effect (shader)
    private int $bloomPoly = 0;
    private int $bloomTexS = 0;
    private int $bloomTexF = 0;
    private int $bloomFX = 0;
    private bool $bloomOK = false;

    // god-rays post-effect (shader)
    private int $godPoly = 0;
    private int $godTex = 0;
    private int $godFX = 0;
    private bool $godOK = false;

    // sounds
    private int $sndBreak = 0;
    private int $sndPlace = 0;
    private int $sndStep = 0;
    private int $sndAmbient = 0;
    private int $ambCh = 0;

    // ===================================================================== run

    public function index(int|string $maxFrames = 0): int
    {
        $max = (int) $maxFrames;
        $e = $this->e = $this->engine;

        $this->loadSettings();

        $e->xKey($this->config->firstKey());
        $e->xSetAntiAliasType($e->xGetMaxAntiAlias());
        $e->xAppTitle('Craft - Xors3d voxel game (PHP)');
        $e->xGraphics3D((int) $this->settings['width'], (int) $this->settings['height'], 32, 0, (int) $this->settings['vsync']);
        $e->xAntiAlias(1);
        $e->xSetTextureFiltering(Constants::TF_POINT);
        $e->xHidePointer();

        $this->cam = new MouseLookCamera($e);
        $this->camH = $this->cam->handle();
        $e->xCameraClsColor($this->camH, 115, 185, 245);
        $e->xCameraRange($this->camH, 0.2, 600);
        $e->xCameraFogColor($this->camH, 115, 185, 245);
        $e->xCameraFogRange($this->camH, 60, 260);

        $this->sun = $e->xCreateLight(Constants::LIGHT_DIRECTIONAL);
        $e->xRotateEntity($this->sun, 50, 30, 0);
        $this->moon = $e->xCreateLight(Constants::LIGHT_DIRECTIONAL);
        $e->xRotateEntity($this->moon, 230, 30, 0);
        $e->xLightColor($this->moon, 0, 0, 0);
        $e->xAmbientLight(120, 120, 130);

        // pool of point lights reassigned each frame to the nearest torches/glowstone
        // (real additive glow around the player's lights, works in dark caves at night)
        for ($i = 0; $i < 5; $i++) {
            $l = $e->xCreateLight(Constants::LIGHT_POINT);
            $e->xLightColor($l, 255, 205, 130);          // warm torchlight
            $e->xLightRange($l, 11.0 * self::BLOCK);
            $e->xHideEntity($l);
            $this->pointLights[] = $l;
        }
        $e->xLoadFont('Arial', 14);

        $this->buildTemplates($e);
        $this->loadIcons($e);
        $this->loadMobTextures($e);
        $this->createSky($e);
        $this->createHand($e, $this->camH);
        $this->pivot = $e->xCreatePivot();
        $this->loadSounds($e);
        $this->setupBloom($e);
        $this->setupGodRays($e);
        $this->applySettings();
        $this->rebuildWorld();

        if ($max > 0) {
            $this->spawnPlayer();
            $this->gameLoop($max);
            $e->xReleaseGraphics();
            return 0;
        }

        if (getenv('CRAFT_SETSHOT')) { $this->settingsMenu(); $e->xReleaseGraphics(); return 0; }

        while (!$this->quit) {
            $action = $this->mainMenu();
            if ($this->quit || $action === 'quit') {
                break;
            }
            if ($action === 'save')     { $this->saveWorld(); continue; }
            if ($action === 'load')     { $this->loadWorld(); continue; }
            if ($action === 'settings') { $this->settingsMenu(); continue; }
            if ($action === 'new')      { $this->rebuildWorld(); $this->status = 'New world generated.'; }
            $this->spawnPlayer();
            $this->gameLoop(0);
        }

        $e->xReleaseGraphics();
        return 0;
    }

    // ================================================================= helpers

    private function closeRequested(): bool
    {
        return (bool) $this->e->xWinMessage('WM_CLOSE');
    }

    private function selectedType(): int
    {
        return $this->hotbar[$this->slot];
    }

    private function spawnPlayer(): void
    {
        $this->px = $this->originX;
        $this->pz = $this->originZ;
        $this->py = (self::MAX_H + 6) * self::BLOCK;
        $this->vy = 0.0;
        $this->onGround = false;
        $this->cam->reset();
        $this->e->xPositionEntity($this->camH, $this->px, $this->py + self::EYE, $this->pz);
        $this->streamCX = PHP_INT_MAX;              // force streaming refresh
        $this->updateStreaming($this->px, $this->pz); // queue the world around spawn
        $this->processStreaming(12, 0);            // build just the near ring now (ground under
                                                   // the player); the rest streams in per-frame
        $this->clearMobs();                        // sheep re-stream around the new spot
        $this->mobTimer = 0;
        $seed = min(4, (int) $this->settings['mobs']);
        for ($i = 0; $i < $seed; $i++) { $this->spawnMobNear(); } // a few right away
    }

    // ================================================================ settings

    private function settingsFile(): string { return dirname(__DIR__, 2) . '/craft-settings.json'; }

    private function loadSettings(): void
    {
        $f = $this->settingsFile();
        if (is_file($f) && ($json = json_decode((string) file_get_contents($f), true)) !== null) {
            foreach ($this->settings as $k => $v) {
                if (isset($json[$k])) {
                    $this->settings[$k] = is_float($v) ? (float) $json[$k] : (is_int($v) ? (int) $json[$k] : $json[$k]);
                }
            }
        }
    }

    private function saveSettings(): void
    {
        @file_put_contents($this->settingsFile(), json_encode($this->settings, JSON_PRETTY_PRINT));
    }

    private function applySettings(): void
    {
        $this->cam->setSensitivity((float) $this->settings['sensitivity']);
        $this->cam->setInvertY((bool) $this->settings['invertY']);
        $this->e->xCameraZoom($this->camH, (float) $this->settings['fov']);
        $this->e->xCameraFogMode($this->camH, (int) $this->settings['fog'] ? 1 : 0);
        if ($this->ambCh !== 0) {
            $this->e->xChannelVolume($this->ambCh, (float) $this->settings['volume'] * 0.6);
        }
        $this->applyRenderDist();
    }

    /** Create the visible sun/moon discs and a few drifting clouds (fog-immune). */
    private function createSky(Engine $e): void
    {
        $sky = dirname(__DIR__, 2) . '/assets/sky/';
        $fxSky = Constants::FX_FULLBRIGHT + Constants::FX_DISABLEFOG;

        $this->sunDisc = $e->xCreateSprite();
        $e->xEntityTexture($this->sunDisc, $e->xLoadTexture($sky . 'sun.png', 1 + 2 + 8));
        $e->xEntityFX($this->sunDisc, $fxSky);
        $e->xScaleSprite($this->sunDisc, 34, 34);

        $this->moonDisc = $e->xCreateSprite();
        $e->xEntityTexture($this->moonDisc, $e->xLoadTexture($sky . 'moon.png', 1 + 2 + 8));
        $e->xEntityFX($this->moonDisc, $fxSky);
        $e->xScaleSprite($this->moonDisc, 26, 26);

        // soft, airy clouds: clusters of overlapping billboard puffs
        $puffTex = $e->xLoadTexture($sky . 'puff.png', 1 + 2 + 8);
        for ($i = 0; $i < 8; $i++) {
            $pivot = $e->xCreatePivot();
            $rx = mt_rand(9, 16);   // cloud radius (blocks)
            $rz = mt_rand(6, 11);
            $puffs = mt_rand(7, 13);
            for ($p = 0; $p < $puffs; $p++) {
                $ox = (mt_rand(-100, 100) / 100.0) * $rx;
                $oz = (mt_rand(-100, 100) / 100.0) * $rz;
                $oy = (mt_rand(-100, 100) / 100.0) * 1.2;
                $size = mt_rand(7, 14);                    // puff diameter (blocks)
                $sp = $e->xCreateSprite();
                $e->xEntityTexture($sp, $puffTex);
                $e->xEntityFX($sp, $fxSky);
                $e->xEntityAlpha($sp, mt_rand(45, 75) / 100.0);
                $e->xScaleSprite($sp, $size * self::BLOCK, $size * self::BLOCK);
                $e->xEntityParent($sp, $pivot);
                $e->xPositionEntity($sp, $ox * self::BLOCK, $oy * self::BLOCK, $oz * self::BLOCK, 0);
                $this->cloudPuffs[] = $sp;
            }
            $this->clouds[] = [
                'pivot' => $pivot,
                'x'     => mt_rand(-20, 140) * self::BLOCK,
                'y'     => (self::MAX_H + mt_rand(10, 15)) * self::BLOCK,
                'z'     => mt_rand(-20, 140) * self::BLOCK,
                'sp'    => (mt_rand(2, 5) / 100.0) * self::BLOCK,
            ];
        }

        $this->createWeather($e, $sky, $fxSky);
    }


    /** Position sun & moon discs relative to the camera, drift the clouds. */
    private function updateSkyObjects(): void
    {
        $e = $this->e;
        $d = (int) $this->settings['renderDist'] * self::BLOCK * 0.9;
        $cxp = $e->xEntityX($this->camH, 1);
        $cyp = $e->xEntityY($this->camH, 1);
        $czp = $e->xEntityZ($this->camH, 1);

        // constant on-screen size regardless of render distance (angular size)
        $e->xScaleSprite($this->sunDisc, $d * 0.095, $d * 0.095);
        $e->xScaleSprite($this->moonDisc, $d * 0.075, $d * 0.075);

        // sun sits opposite the sun-light ray direction
        $e->xTFormVector(0, 0, 1, $this->sun, 0);
        $fx = $e->xTFormedX(); $fy = $e->xTFormedY(); $fz = $e->xTFormedZ();
        $e->xPositionEntity($this->sunDisc, $cxp - $fx * $d, $cyp - $fy * $d, $czp - $fz * $d);
        (-$fy > -0.05) ? $e->xShowEntity($this->sunDisc) : $e->xHideEntity($this->sunDisc);

        // moon sits opposite the sun (along the moon-light ray direction)
        $e->xTFormVector(0, 0, 1, $this->moon, 0);
        $mx = $e->xTFormedX(); $my = $e->xTFormedY(); $mz = $e->xTFormedZ();
        $e->xPositionEntity($this->moonDisc, $cxp - $mx * $d, $cyp - $my * $d, $czp - $mz * $d);
        (-$my > -0.05) ? $e->xShowEntity($this->moonDisc) : $e->xHideEntity($this->moonDisc);

        // clouds: tint by time of day so they aren't glaring white at night
        $v = (int) (85 + $this->dayF * 170);
        foreach ($this->cloudPuffs as $sp) {
            $e->xEntityColor($sp, $v, $v, min(255, $v + 8));
        }

        $lo = $this->px - 70 * self::BLOCK; $hi = $this->px + 70 * self::BLOCK;
        foreach ($this->clouds as &$c) {
            $c['x'] += $c['sp'] * $this->dt;
            if ($c['x'] > $hi) { $c['x'] = $lo; }
            $e->xPositionEntity($c['pivot'], $c['x'], $c['y'], $c['z']);
        }
        unset($c);
    }

    private function updateSky(): void
    {
        $e = $this->e;

        if (!(int) $this->settings['daynight']) {
            $this->dayF = 1.0;
            $e->xCameraClsColor($this->camH, 115, 185, 245);
            $e->xCameraFogColor($this->camH, 115, 185, 245);
            $e->xRotateEntity($this->sun, 50, 30, 0);
            $e->xLightColor($this->sun, 255, 250, 235);
            $e->xLightColor($this->moon, 0, 0, 0);
            $e->xAmbientLight(120, 120, 130);
            return;
        }

        $t = getenv('CRAFT_TIME');
        $frac = ($t !== false) ? (float) $t : fmod($e->xMillisecs() / 120000.0, 1.0);
        $ang = $frac * 360.0;
        $e->xRotateEntity($this->sun, $ang, 30, 0);
        $e->xRotateEntity($this->moon, $ang + 180.0, 30, 0); // opposite the sun

        $day   = max(0.0, sin(deg2rad($ang)));   // 1 at noon, 0 at night
        $night = max(0.0, -sin(deg2rad($ang)));  // 1 at midnight, 0 at day
        $this->dayF = $day;

        // sun bright by day, moon dim-blue by night
        $e->xLightColor($this->sun, (int) (255 * $day), (int) (250 * $day), (int) (235 * $day));
        $e->xLightColor($this->moon, (int) (80 * $night), (int) (95 * $night), (int) (150 * $night));

        // sky: bright blue by day -> deep blue at night. Use sqrt(day) so the sky reads
        // blue for most of the daytime instead of dimming to grey at low sun angles.
        $sd = sqrt($day);
        $r = 30 + $sd * 85;   //  30 -> 115
        $g = 45 + $sd * 145;  //  45 -> 190
        $b = 78 + $sd * 172;  //  78 -> 250 (kept high for a blue tint)

        // overcast: pull the sky toward flat grey and dim the sun while it rains/snows
        $w = $this->wetness;
        if ($w > 0.001) {
            $gr = 70 + $day * 55; // grey level that tracks day/night
            $r = $r + ($gr - $r) * $w; $g = $g + ($gr - $g) * $w; $b = $b + ($gr * 1.05 - $b) * $w;
            $dim = 1.0 - 0.5 * $w;
            $e->xLightColor($this->sun, (int) (255 * $day * $dim), (int) (250 * $day * $dim), (int) (235 * $day * $dim));
        }
        $e->xCameraClsColor($this->camH, (int) $r, (int) $g, (int) $b);
        $e->xCameraFogColor($this->camH, (int) $r, (int) $g, (int) $b);

        // keep night navigable (moonlit), bright at noon; a touch dimmer when overcast
        $amb = (45 + $day * 80) * (1.0 - 0.25 * $w);
        $ar = $amb; $ag = $amb; $ab = $amb * 1.25; // slightly blue ambient
        // rain: cool sky-coloured sheen so wet surfaces glisten (fake reflection)
        if ($this->weather === 1) {
            $sheen = $w * (0.35 + $day * 0.4);
            $ar += (150 - $ar) * $sheen * 0.5;
            $ag += (175 - $ag) * $sheen * 0.6;
            $ab += (210 - $ab) * $sheen * 0.8;
        }
        $e->xAmbientLight((int) $ar, (int) $ag, (int) min(255.0, $ab));
    }

    // =================================================================== sound

    private function loadSounds(Engine $e): void
    {
        $dir = dirname(__DIR__, 2) . '/assets/sounds/';
        if (is_file($dir . 'break.wav'))   { $this->sndBreak   = $e->xLoadSound($dir . 'break.wav'); }
        if (is_file($dir . 'place.wav'))   { $this->sndPlace   = $e->xLoadSound($dir . 'place.wav'); }
        if (is_file($dir . 'step.wav'))    { $this->sndStep    = $e->xLoadSound($dir . 'step.wav'); }
        if (is_file($dir . 'ambient.wav')) {
            $this->sndAmbient = $e->xLoadSound($dir . 'ambient.wav');
            if ($this->sndAmbient !== 0) {
                $e->xLoopSound($this->sndAmbient);
                $this->ambCh = $e->xPlaySound($this->sndAmbient);
            }
        }
    }

    private function play(int $sound): void
    {
        $vol = (float) $this->settings['volume'];
        if ($sound === 0 || $vol <= 0.0) {
            return;
        }
        $this->e->xSoundVolume($sound, $vol);
        $this->e->xPlaySound($sound);
    }

    // =================================================================== setup

    private function buildTemplates(Engine $e): void
    {
        $base = dirname(__DIR__, 2) . '/assets/blocks/';
        foreach (self::TYPES as $id => [$name, $file]) {
            $cube = $e->xCreateCube();
            if ($id === 1) {
                $w = $e->xMeshWidth($cube);
                $this->scale = $w > 0.0 ? self::BLOCK / $w : 1.0;
            }
            $e->xScaleEntity($cube, $this->scale, $this->scale, $this->scale);
            // glass loads as a MASKED texture: fully-transparent texels are discarded so
            // you see straight through the pane, the frame stays solid (crisp windows).
            $texture = ($id === 10 || $id === self::DOOR)
                ? $e->xLoadTexture($base . $file, 1 + 4 + 8)   // color + masked + mipmap (glass/door)
                : $e->xLoadTexture($base . $file);
            $this->tex[$id] = $texture;
            $e->xEntityTexture($cube, $texture);
            if ($id === 11) { $e->xEntityFX($cube, 1); } // glowstone: fullbright
            $e->xHideEntity($cube);
            $this->template[$id] = $cube;

            // brush per type for the merged chunk-mesh surfaces
            $b = $e->xCreateBrush();
            $e->xBrushTexture($b, $texture);
            $this->brush[$id] = $b;
        }

        // animated translucent water
        $this->waterTex = $e->xLoadAnimTexture($base . 'water.png', 1, 16, 16, 0, 32);
        $this->waterTpl = $e->xCreateCube();
        $e->xScaleEntity($this->waterTpl, $this->scale, $this->scale, $this->scale);
        $e->xEntityColor($this->waterTpl, 120, 160, 255);
        $e->xEntityAlpha($this->waterTpl, 0.7);
        $e->xEntityTexture($this->waterTpl, $this->waterTex);
        $e->xHideEntity($this->waterTpl);
    }

    private function createHand(Engine $e, int $camera): void
    {
        $this->hand = $e->xCreateCube();
        $s = $this->scale * 0.22;
        $e->xScaleEntity($this->hand, $s, $s, $s);
        $e->xEntityParent($this->hand, $camera);
        $e->xEntityFX($this->hand, 1);
        $e->xPositionEntity($this->hand, 0.95, -0.75, 2.6, 0);
        $e->xRotateEntity($this->hand, 15, 35, 0, 0);
        $this->refreshHand($e);
    }

    private function refreshHand(Engine $e): void
    {
        if ($this->hand !== 0) {
            $e->xEntityTexture($this->hand, $this->tex[$this->selectedType()]);
        }
    }

    // ============================================================ world (gen)

    /** Free all instantiated entities; keep the data model (height/edits). */
    private function clearWorld(): void
    {
        $e = $this->e;
        $this->clearMobs();
        foreach ($this->chunk as $list) {
            foreach ($list as $h) { $e->xFreeEntity($h); }
        }
        $this->chunk = $this->chunkMesh = $this->meshCk = $this->water = $this->loaded = [];
        $this->streamCX = PHP_INT_MAX;
        $this->streamCZ = PHP_INT_MAX;
    }

    private function rebuildWorld(): void
    {
        $this->clearWorld();
        $this->edits = [];
        $this->editsByChunk = [];
        $this->lightCells = [];
        $this->treeGen = [];
        $this->height = [];
        $this->biome = [];
        $this->generateData();
    }

    /**
     * Infinite world: nothing is precomputed. The height map, ores and trees are
     * generated procedurally per column/chunk on demand as the player explores
     * (see heightAt / groundType / loadChunk). Only a new random seed + mobs.
     */
    private function generateData(): void
    {
        $this->seed = mt_rand() / mt_getrandmax() * 1000.0;
        $this->starterKit();
        $this->buildStructures();
    }

    // ---------------------------------------------------- spawn structures

    /** Fill a solid box of one block type into the edit overlay. */
    private function fillBox(int $x0, int $y0, int $z0, int $x1, int $y1, int $z1, int $t): void
    {
        for ($x = $x0; $x <= $x1; $x++) {
            for ($y = $y0; $y <= $y1; $y++) {
                for ($z = $z0; $z <= $z1; $z++) { $this->setEdit($x, $y, $z, $t); }
            }
        }
    }

    /** Vertical walls only (perimeter) between two corners. */
    private function walls(int $x0, int $y0, int $z0, int $x1, int $y1, int $z1, int $t): void
    {
        for ($x = $x0; $x <= $x1; $x++) {
            for ($z = $z0; $z <= $z1; $z++) {
                if ($x !== $x0 && $x !== $x1 && $z !== $z0 && $z !== $z1) { continue; }
                for ($y = $y0; $y <= $y1; $y++) { $this->setEdit($x, $y, $z, $t); }
            }
        }
    }

    /** Radius (blocks) around spawn kept clear of trees for the plaza + buildings. */
    private const PLAZA_R = 48;

    /** Load a converted blueprint (assets/structures/<name>.json), cached. */
    private function loadStruct(string $name): ?array
    {
        static $cache = [];
        if (array_key_exists($name, $cache)) { return $cache[$name]; }
        $f = dirname(__DIR__, 2) . '/assets/structures/' . $name . '.json';
        $d = is_file($f) ? json_decode((string) file_get_contents($f), true) : null;
        return $cache[$name] = (is_array($d) ? $d : null);
    }

    /**
     * Stamp a converted blueprint with its min-corner at (ox, base+1, oz). When $level is
     * true a flat grass pad is levelled under it (for ground buildings); when false the
     * blocks are placed as-is (for floating set pieces like the sky island).
     */
    private function placeStruct(string $name, int $ox, int $base, int $oz, bool $level = true): void
    {
        $s = $this->loadStruct($name);
        if ($s === null) { return; }
        if ($level) {
            $w = (int) $s['w']; $d = (int) $s['d'];
            for ($x = $ox - 1; $x <= $ox + $w; $x++) {
                for ($z = $oz - 1; $z <= $oz + $d; $z++) {
                    $this->setEdit($x, $base - 1, $z, 2);
                    $this->setEdit($x, $base, $z, 1);
                    for ($y = $base + 1; $y <= $base + 12; $y++) { $this->setEdit($x, $y, $z, 0); }
                }
            }
        }
        foreach ($s['blocks'] as [$dx, $dy, $dz, $t]) {
            $this->setEdit($ox + (int) $dx, $base + 1 + (int) $dy, $oz + (int) $dz, (int) $t);
        }
    }

    /** A glowstone lamp on a short post (a "torch" light for the plaza). */
    private function lampPost(int $x, int $base, int $z): void
    {
        $this->setEdit($x, $base + 1, $z, 8);   // log post
        $this->setEdit($x, $base + 2, $z, 8);
        $this->setEdit($x, $base + 3, $z, 11);  // glowstone lamp on top
    }

    /** Build the spawn plaza with imported blueprint buildings + a castle, tower and lamps. */
    private function buildStructures(): void
    {
        $ox = $this->cellOf($this->originX);
        $oz = $this->cellOf($this->originZ);
        $base = max(self::SEA + 2, $this->heightAt($ox, $oz));

        // small clear pad where the player lands
        for ($x = $ox - 3; $x <= $ox + 3; $x++) {
            for ($z = $oz - 3; $z <= $oz + 3; $z++) {
                $this->setEdit($x, $base - 1, $z, 2);
                $this->setEdit($x, $base, $z, 1);
                for ($y = $base + 1; $y <= $base + 12; $y++) { $this->setEdit($x, $y, $z, 0); }
            }
        }

        // imported Axiom blueprints (converted from Default-assets/schematics)
        $this->placeStruct('birch_house',    $ox - 40, $base, $oz - 16);
        $this->placeStruct('medieval_house', $ox + 12, $base, $oz - 18);
        $this->placeStruct('temple',         $ox - 18, $base, $oz + 14);

        // hand-built castle + watchtower
        $this->buildCastle($ox + 12, $base, $oz + 10);
        $this->buildTower($ox - 4, $base, $oz + 6);

        // lamp posts around the central plaza for night-time light
        foreach ([[-8, -8], [8, -8], [-8, 8], [8, 8], [0, -10], [0, 10]] as [$lx, $lz]) {
            $this->lampPost($ox + $lx, $base, $oz + $lz);
        }

        // a giant floating island in the sky over the village (scenic set piece)
        $isl = $this->loadStruct('island');
        if ($isl !== null) {
            $floatY = $base + 40; // bottom of the island, high above the plaza
            $ix = $ox - (int) ((int) $isl['w'] / 2) - 20; // offset to one side
            $iz = $oz - (int) ((int) $isl['d'] / 2);
            $this->placeStruct('island', $ix, $floatY, $iz, false);
        }
    }

    /** Stone-brick castle: walls, battlements, four corner towers, gate + throne room. */
    private function buildCastle(int $x0, int $base, int $z0): void
    {
        $w = 10; $d = 10; $wh = 6;
        $x1 = $x0 + $w; $z1 = $z0 + $d;
        $this->fillBox($x0, $base, $z0, $x1, $base, $z1, 15);          // cobblestone floor
        $this->walls($x0, $base + 1, $z0, $x1, $base + $wh, $z1, 16);  // stone-brick walls
        // battlements (merlons) along the top edge, every other block
        for ($x = $x0; $x <= $x1; $x++) {
            for ($z = $z0; $z <= $z1; $z++) {
                if ($x !== $x0 && $x !== $x1 && $z !== $z0 && $z !== $z1) { continue; }
                if ((($x + $z) & 1) === 0) { $this->setEdit($x, $base + $wh + 1, $z, 16); }
            }
        }
        // taller corner towers
        foreach ([[$x0, $z0], [$x1, $z0], [$x0, $z1], [$x1, $z1]] as [$cx, $cz]) {
            $tx0 = max($x0, $cx - 1); $tx1 = min($x1, $cx + 1);
            $tz0 = max($z0, $cz - 1); $tz1 = min($z1, $cz + 1);
            $this->walls($tx0, $base + 1, $tz0, $tx1, $base + $wh + 3, $tz1, 16);
            $this->fillBox($tx0, $base + $wh + 3, $tz0, $tx1, $base + $wh + 3, $tz1, 22); // chiseled cap
        }
        // gate: 3-wide, 3-high opening in the front (-z) wall
        $gx = $x0 + 5;
        $this->fillBox($gx - 1, $base + 1, $z0, $gx + 1, $base + 3, $z0, 0);
        // interior throne room: glowstone lights, bookshelves and a throne
        $this->setEdit($x0 + 3, $base + $wh, $z0 + 3, 11);
        $this->setEdit($x1 - 3, $base + $wh, $z1 - 3, 11);
        $this->fillBox($x0 + 1, $base + 1, $z1 - 1, $x0 + 3, $base + 2, $z1 - 1, 19); // bookshelves
        $this->fillBox($x1 - 1, $base + 1, $z1 - 3, $x1 - 1, $base + 2, $z1 - 1, 19);
        $this->setEdit($x0 + 5, $base + 1, $z1 - 2, 22);            // throne base
        $this->setEdit($x0 + 5, $base + 2, $z1 - 2, 20);            // throne seat (red)
    }

    /** Slim stone watchtower with a glowstone beacon on top. */
    private function buildTower(int $cx, int $base, int $cz): void
    {
        $h = 10;
        $this->walls($cx - 1, $base + 1, $cz - 1, $cx + 1, $base + $h, $cz + 1, 16);
        $this->fillBox($cx - 1, $base, $cz - 1, $cx + 1, $base, $cz + 1, 15);        // base
        // door
        $this->setEdit($cx, $base + 1, $cz - 1, 0); $this->setEdit($cx, $base + 2, $cz - 1, 0);
        // battlement cap + beacon
        for ($x = $cx - 1; $x <= $cx + 1; $x++) {
            for ($z = $cz - 1; $z <= $cz + 1; $z++) {
                if ((($x + $z) & 1) === 0) { $this->setEdit($x, $base + $h + 1, $z, 22); }
            }
        }
        $this->setEdit($cx, $base + $h, $cz, 11); // glowstone beacon inside the top
    }

    /** Minimum spacing (blocks) between tree trunks so canopies never overlap. */
    private const TREE_DIST = 4;

    /**
     * Is (x,z) a tree candidate? Returns >=0 (its priority) if a trunk may grow here,
     * or -1 otherwise. Pure function of position so neighbouring chunks agree.
     */
    private function treeStrength(int $x, int $z): float
    {
        // keep the spawn plaza (and its buildings) clear of trees
        if (abs($x - $this->cellOf($this->originX)) <= self::PLAZA_R
            && abs($z - $this->cellOf($this->originZ)) <= self::PLAZA_R) { return -1.0; }
        $h = $this->heightAt($x, $z);
        if ($h <= self::SEA || $h >= self::SNOW) { return -1.0; }
        $b = $this->biomeVal($x, $z);
        if ($b < 0.30)      { return -1.0; }     // desert: no trees
        elseif ($b < 0.55)  { $prob = 0.012; }   // plains: sparse
        elseif ($b < 0.72)  { $prob = 0.06;  }   // forest: dense
        else                { $prob = 0.008; }   // mountains: rare
        if ($this->hash3($x, 7, $z) >= $prob * (float) $this->settings['trees']) { return -1.0; }
        return $this->hash3($x, 13, $z);          // independent priority for spacing
    }

    /** Deterministically populate a chunk's trees into the edit overlay (once). */
    private function genTrees(int $cx, int $cz): void
    {
        $x0 = $cx * self::CH; $z0 = $cz * self::CH;
        $D = self::TREE_DIST;
        for ($x = $x0; $x < $x0 + self::CH; $x++) {
            for ($z = $z0; $z < $z0 + self::CH; $z++) {
                $pri = $this->treeStrength($x, $z);
                if ($pri < 0.0) { continue; }
                // Poisson-disk spacing: only plant if this is the strongest candidate in
                // a TREE_DIST radius, so no two trunks land close enough to overlap.
                $win = true;
                for ($nx = $x - $D; $nx <= $x + $D && $win; $nx++) {
                    for ($nz = $z - $D; $nz <= $z + $D; $nz++) {
                        if ($nx === $x && $nz === $z) { continue; }
                        if ($this->treeStrength($nx, $nz) > $pri) { $win = false; break; }
                    }
                }
                if ($win) { $this->plantTreeData($x, $this->heightAt($x, $z) + 1, $z); }
            }
        }
    }

    /** Blueprint buildings that spawn randomly across the world (small/medium only;
     *  the huge cathedral & harbour HQ are excluded to avoid generation hitches). */
    private const WILD_STRUCTURES = [
        'rustic_house', 'house3', 'medieval_house', 'birch_house', 'water_tank',
        'temple', 'castle_grau', 'gate',
    ];
    private const SGRID = 10; // one candidate per 10x10-chunk cell; origin kept to the
                              // central 4x4 so neighbours stay >=7 chunks (56 blocks) apart

    /**
     * Procedural landmarks: at most one blueprint building per SGRID x SGRID chunk cell,
     * at a hashed origin chunk, on flat-ish dry ground. Deterministic from world seed so
     * it regenerates identically. Stamped when that origin chunk first generates.
     */
    private function genStructures(int $cx, int $cz): void
    {
        $g = self::SGRID;
        $gx = (int) floor($cx / $g); $gz = (int) floor($cz / $g);
        // hashed origin within the central 4x4 of the cell (offset 3..6) so structures
        // in neighbouring cells cannot land closer than ~7 chunks to each other
        $ox = $gx * $g + 3 + (int) ($this->hash3($gx, 1, $gz) * 4);
        $oz = $gz * $g + 3 + (int) ($this->hash3($gx, 2, $gz) * 4);
        if ($cx !== $ox || $cz !== $oz) { return; }
        if ($this->hash3($gx, 3, $gz) >= 0.55) { return; }   // ~55% of cells stay empty

        $wx = $ox * self::CH; $wz = $oz * self::CH;
        // keep clear of the spawn plaza
        if (abs($wx - $this->cellOf($this->originX)) < self::PLAZA_R + 24
            && abs($wz - $this->cellOf($this->originZ)) < self::PLAZA_R + 24) { return; }
        $base = $this->heightAt($wx, $wz);
        if ($base < self::SEA + 1) { return; }               // not in water
        if ($this->biomeVal($wx, $wz) >= 0.82) { return; }   // not on steep mountains

        $list = self::WILD_STRUCTURES;
        $pick = $list[(int) ($this->hash3($gx, 5, $gz) * count($list))];
        $this->placeStruct($pick, $wx, $base, $wz);
    }

    /** Spawn a small burst of textured cube shards when a block is broken. */
    private function spawnBreakParticles(int $x, int $y, int $z, int $type): void
    {
        $e = $this->e; $B = self::BLOCK;
        $tex = $this->tex[$type] ?? 0;
        if ($tex === 0) { return; }
        $cx = $x * $B; $cy = $y * $B; $cz = $z * $B;
        for ($i = 0; $i < 7; $i++) {
            $c = $e->xCreateCube();
            $s = $this->scale * (0.12 + mt_rand(0, 8) / 100.0);
            $e->xScaleEntity($c, $s, $s, $s);
            $e->xEntityTexture($c, $tex);
            $ox = (mt_rand(-40, 40) / 100.0) * $B; $oy = (mt_rand(-30, 40) / 100.0) * $B; $oz = (mt_rand(-40, 40) / 100.0) * $B;
            $e->xPositionEntity($c, $cx + $ox, $cy + $oy, $cz + $oz);
            $this->particles[] = [
                'ent' => $c, 'x' => $cx + $ox, 'y' => $cy + $oy, 'z' => $cz + $oz,
                'vx' => (mt_rand(-15, 15) / 100.0) * $B, 'vy' => (mt_rand(15, 38) / 100.0) * $B,
                'vz' => (mt_rand(-15, 15) / 100.0) * $B, 'life' => mt_rand(18, 30),
            ];
        }
        // cap the pool: drop the oldest bursts if it grows too large
        while (count($this->particles) > 140) {
            $p = array_shift($this->particles);
            $e->xFreeEntity($p['ent']);
        }
    }

    /** Advance and expire block-break particles (gravity + fade to removal). */
    private function updateParticles(): void
    {
        if ($this->particles === []) { return; }
        $e = $this->e; $dt = $this->dt;
        foreach ($this->particles as $i => &$p) {
            $p['vy'] -= self::G * 0.6 * $dt;
            $p['x'] += $p['vx'] * $dt; $p['y'] += $p['vy'] * $dt; $p['z'] += $p['vz'] * $dt;
            $p['life'] -= $dt;
            if ($p['life'] <= 0) { $e->xFreeEntity($p['ent']); unset($this->particles[$i]); continue; }
            $e->xPositionEntity($p['ent'], $p['x'], $p['y'], $p['z']);
        }
        unset($p);
    }

    /** Reassign the point-light pool to the nearest torches/glowstone around the player. */
    private function updatePointLights(): void
    {
        if ($this->pointLights === []) { return; }
        $e = $this->e; $B = self::BLOCK;
        $reach = 26.0 * $B; $reach2 = $reach * $reach;
        $px = $this->px; $py = $this->py; $pz = $this->pz;
        $near = [];
        foreach ($this->lightCells as [$x, $y, $z]) {
            $wx = $x * $B; $wy = $y * $B; $wz = $z * $B;
            $dx = $wx - $px; $dy = $wy - $py; $dz = $wz - $pz;
            $d2 = $dx * $dx + $dy * $dy + $dz * $dz;
            if ($d2 < $reach2) { $near[] = [$d2, $wx, $wy, $wz]; }
        }
        sort($near); // nearest first (by squared distance)
        foreach ($this->pointLights as $i => $l) {
            if (isset($near[$i])) {
                [, $wx, $wy, $wz] = $near[$i];
                $e->xPositionEntity($l, $wx, $wy + $B * 0.3, $wz);
                $e->xShowEntity($l);
            } else {
                $e->xHideEntity($l);
            }
        }
    }

    private function clearMobs(): void
    {
        foreach ($this->mobs as $m) {
            foreach ($m['parts'] as $p) { $this->e->xFreeEntity($p); }
            $this->e->xFreeEntity($m['pivot']);
        }
        $this->mobs = [];
    }

    // =============================================================== hud icons

    private function loadIcons(Engine $e): void
    {
        $base = dirname(__DIR__, 2) . '/assets/blocks/';
        foreach (self::TYPES as $id => [$name, $file]) {
            if ($id === 7) { continue; } // leaves not placeable/selectable
            $img = $e->xLoadImage($base . $file);
            $e->xResizeImage($img, 44, 44);
            $this->icon[$id] = $img;
        }
    }

    /** All block types that can be selected in the crafting/block menu. */
    private function craftable(): array
    {
        $ids = array_keys(self::TYPES);
        return array_values(array_filter($ids, fn($id) => $id !== 7)); // exclude leaves
    }

    private function exposedBottom(int $x, int $z): int
    {
        $min = $this->heightAt($x, $z);
        foreach ([[1, 0], [-1, 0], [0, 1], [0, -1]] as [$dx, $dz]) {
            $nx = $x + $dx; $nz = $z + $dz;
            $nh = $this->heightAt($nx, $nz);
            $min = min($min, $nh);
        }
        return max(0, $min);
    }

    /** Block types that snow settles on top of (natural ground + built stone/brick/wood). */
    private function coverable(int $type): bool
    {
        // grass, dirt, stone, brick, wood, snow, sand, glowstone, ores
        return in_array($type, [1, 2, 3, 4, 5, 6, 9, 11, 12, 13, 14], true);
    }

    private function setEdit(int $x, int $y, int $z, int $type): void
    {
        $k = "$x,$y,$z";
        $this->edits[$k] = $type;
        $ck = $this->cdiv($x) . "," . $this->cdiv($z);
        $this->editsByChunk[$ck][$k] = $type;
        if ($this->trackSpill) { $this->treeSpill[$ck] = true; }
        if ($type === 11) { $this->lightCells[$k] = [$x, $y, $z]; } // glowstone = light source
        else { unset($this->lightCells[$k]); }
    }

    /** Bake a tree into the edit overlay (streamed in with its chunk). */
    private function plantTreeData(int $x, int $y, int $z): void
    {
        $trunk = mt_rand(3, 4);
        for ($i = 0; $i < $trunk; $i++) { $this->setEdit($x, $y + $i, $z, 8); }
        $top = $y + $trunk;
        for ($dy = -1; $dy <= 0; $dy++) {
            for ($dx = -2; $dx <= 2; $dx++) {
                for ($dz = -2; $dz <= 2; $dz++) {
                    if (abs($dx) === 2 && abs($dz) === 2) { continue; }
                    $this->setEdit($x + $dx, $top + $dy, $z + $dz, 7);
                }
            }
        }
        foreach ([[0, 0], [1, 0], [-1, 0], [0, 1], [0, -1]] as [$dx, $dz]) {
            $this->setEdit($x + $dx, $top + 1, $z + $dz, 7);
        }
    }

    // ============================================================ world (ops)

    private function key(int $x, int $y, int $z): string { return "$x,$y,$z"; }
    private function cdiv(int $v): int { return (int) floor($v / self::CH); }

    /** Final block type at a cell from the data model (edits over generation). 0 = air. */
    private function solidType(int $x, int $y, int $z): int
    {
        // solid "bedrock" below the world so the underside of the terrain is never meshed
        // (no wasted bottom faces you'd only ever see by flying under the map)
        if ($y < 0) { return 3; }
        $k = "$x,$y,$z";
        if (array_key_exists($k, $this->edits)) {
            $t = $this->edits[$k];
            if ($t === self::DOOR && ($this->doorOpen[$k] ?? false)) { return 0; } // open door = passable
            return $t;
        }
        $h = $this->heightAt($x, $z);
        if ($y <= $h) {
            // carve caves below the surface crust (top block stays solid so no surface holes)
            if ($y >= 2 && $y <= $h - 2 && $this->caveAt($x, $y, $z)) { return 0; }
            return $this->groundType($x, $y, $z);
        }
        return 0;
    }

    // =================================================================== bloom

    private function setupBloom(Engine $e): void
    {
        $fx = $this->config->media('Shaders/Bloom.fx');
        if (!is_file($fx)) { $this->bloomOK = false; return; }
        $this->bloomFX = $e->xLoadFXFile($fx);
        if (!$e->xValidateEffectTechnique($this->bloomFX, 'Diffuse')) {
            $this->bloomOK = false;   // GPU can't run it -> silently skip
            return;
        }
        $w = (int) $this->settings['width'];
        $h = (int) $this->settings['height'];
        $this->bloomPoly = $e->xCreatePostEffectPoly($this->camH, 1);
        $this->bloomTexS = $e->xCreateTexture(256, 256);
        $this->bloomTexF = $e->xCreateTexture($w, $h);
        $e->xSetEntityEffect($this->bloomPoly, $this->bloomFX);
        $e->xSetEffectTechnique($this->bloomPoly, 'Diffuse');
        $e->xSetEffectMatrixSemantic($this->bloomPoly, 'MatWorldViewProj', Constants::WORLDVIEWPROJ);
        $e->xSetEffectTexture($this->bloomPoly, 'tDiffuse', $this->bloomTexS);
        $e->xSetEffectTexture($this->bloomPoly, 'tEmissive', $this->bloomTexF);
        $this->bloomOK = true;
    }

    /** Bright-pass + separable blur bloom, run as a post effect over the frame. */
    private function renderBloom(): void
    {
        if (!$this->bloomOK || !(int) $this->settings['bloom']) { return; }
        $e = $this->e;
        $w = (int) $this->settings['width'];
        $h = (int) $this->settings['height'];
        $e->xStretchBackBuffer($this->bloomTexS, 0, 0, 256, 256, 0);
        $e->xStretchBackBuffer($this->bloomTexF, 0, 0, $w, $h, 0);
        $e->xSetEffectTechnique($this->bloomPoly, 'Diffuse');  $e->xRenderPostEffect($this->bloomPoly);
        $e->xStretchBackBuffer($this->bloomTexS, 0, 0, 256, 256, 0);
        $e->xSetEffectTechnique($this->bloomPoly, 'DiffuseH'); $e->xRenderPostEffect($this->bloomPoly);
        $e->xStretchBackBuffer($this->bloomTexS, 0, 0, 256, 256, 0);
        $e->xSetEffectTechnique($this->bloomPoly, 'DiffuseV'); $e->xRenderPostEffect($this->bloomPoly);
    }

    // ================================================================ god rays

    private function setupGodRays(Engine $e): void
    {
        $fx = dirname(__DIR__, 2) . '/assets/shaders/GodRays.fx';
        if (!is_file($fx)) { $this->godOK = false; return; }
        $this->godFX = $e->xLoadFXFile($fx);
        if (!$e->xValidateEffectTechnique($this->godFX, 'Rays')) {
            $this->godOK = false;   // GPU/shader model unsupported -> skip
            return;
        }
        $w = (int) $this->settings['width'];
        $h = (int) $this->settings['height'];
        $this->godPoly = $e->xCreatePostEffectPoly($this->camH, 1);
        $this->godTex  = $e->xCreateTexture($w, $h);
        $e->xSetEntityEffect($this->godPoly, $this->godFX);
        $e->xSetEffectTechnique($this->godPoly, 'Rays');
        $e->xSetEffectMatrixSemantic($this->godPoly, 'MatWorldViewProj', Constants::WORLDVIEWPROJ);
        $e->xSetEffectTexture($this->godPoly, 'tScene', $this->godTex);
        $e->xSetEffectFloat($this->godPoly, 'Density', 0.88);
        $e->xSetEffectFloat($this->godPoly, 'Decay', 0.965);
        $e->xSetEffectFloat($this->godPoly, 'Weight', 0.45);
        $e->xSetEffectFloat($this->godPoly, 'Threshold', 0.8);
        $this->godOK = true;
    }

    /** Radial light shafts from the sun, when it is on screen. */
    private function renderGodRays(): void
    {
        if (!$this->godOK || !(int) $this->settings['godrays'] || $this->dayF <= 0.05) {
            return;
        }
        $e = $this->e;
        $w = (int) $this->settings['width'];
        $h = (int) $this->settings['height'];

        // is the sun in front of the camera?
        $sx = $e->xEntityX($this->sunDisc, 1);
        $sy = $e->xEntityY($this->sunDisc, 1);
        $sz = $e->xEntityZ($this->sunDisc, 1);
        $e->xTFormVector(0, 0, 1, $this->camH, 0);
        $fwx = $e->xTFormedX(); $fwy = $e->xTFormedY(); $fwz = $e->xTFormedZ();
        $tx = $sx - $e->xEntityX($this->camH, 1);
        $ty = $sy - $e->xEntityY($this->camH, 1);
        $tz = $sz - $e->xEntityZ($this->camH, 1);
        if ($fwx * $tx + $fwy * $ty + $fwz * $tz <= 0.0) { return; } // sun behind camera

        $e->xCameraProject($this->camH, $sx, $sy, $sz);
        $u = $e->xProjectedX() / $w;
        $v = $e->xProjectedY() / $h;
        if ($u < -0.6 || $u > 1.6 || $v < -0.6 || $v > 1.6) { return; } // far off-screen

        $e->xSetEffectVector($this->godPoly, 'SunUV', $u, $v, 0, 0);
        $e->xSetEffectVector($this->godPoly, 'RayColor', 1.0, 0.92, 0.65, 0);

        $e->xStretchBackBuffer($this->godTex, 0, 0, $w, $h, 0);
        $e->xSetEffectTechnique($this->godPoly, 'Rays');
        $e->xRenderPostEffect($this->godPoly);
    }

    /** Rebuild the chunk containing (x,z) plus horizontal neighbours (border faces). */
    private function rebuildAround(int $x, int $z): void
    {
        $done = [];
        foreach ([[0, 0], [1, 0], [-1, 0], [0, 1], [0, -1]] as [$dx, $dz]) {
            $cx = $this->cdiv($x + $dx); $cz = $this->cdiv($z + $dz);
            $ck = "$cx,$cz";
            if (!isset($done[$ck])) { $done[$ck] = true; $this->rebuildChunk($cx, $cz); }
        }
    }

    private function destroyAt(Engine $e, int $x, int $y, int $z): void
    {
        $type = $this->solidType($x, $y, $z);
        if ($type <= 0) { return; }
        $this->spawnBreakParticles($x, $y, $z, $type);
        $this->invAdd($this->dropFor($type)); // mined block drops into the inventory
        $this->setEdit($x, $y, $z, 0); // record removal in the data model
        $this->play($this->sndBreak);
        $this->rebuildAround($x, $z);
    }

    private function placeAt(Engine $e, int $x, int $y, int $z, int $type): void
    {
        if ($y < 0 || $y > self::Y_MAX) { return; }
        if ($this->solidType($x, $y, $z) > 0) { return; }
        if ($this->invCount($type) <= 0) { return; }  // need the block in the inventory
        $this->invAdd($type, -1);
        $this->setEdit($x, $y, $z, $type);
        if ($type === self::DOOR) {                         // doors are 2 blocks tall
            if ($this->solidType($x, $y + 1, $z) <= 0) { $this->setEdit($x, $y + 1, $z, self::DOOR); }
            $this->doorOpen["$x,$y,$z"] = false;
            $this->doorOpen[($x) . ',' . ($y + 1) . ',' . ($z)] = false;
        }
        $this->play($this->sndPlace);
        $this->rebuildAround($x, $z);
    }

    /** Toggle the door at (x,y,z) and its vertical partner (open/close), rebuild + sound. */
    private function toggleDoor(int $x, int $y, int $z): bool
    {
        if (($this->edits["$x,$y,$z"] ?? -1) !== self::DOOR) { return false; }
        $cells = ["$x,$y,$z"];
        if (($this->edits[($x).','.($y + 1).','.($z)] ?? -1) === self::DOOR) { $cells[] = ($x).','.($y + 1).','.($z); }
        if (($this->edits[($x).','.($y - 1).','.($z)] ?? -1) === self::DOOR) { $cells[] = ($x).','.($y - 1).','.($z); }
        $open = !($this->doorOpen["$x,$y,$z"] ?? false);
        foreach ($cells as $c) { $this->doorOpen[$c] = $open; }
        $this->play($open ? $this->sndPlace : $this->sndBreak);
        $this->rebuildAround($x, $z);
        return true;
    }

    private function faceOffset(Engine $e): array
    {
        $nx = $e->xPickedNX(); $ny = $e->xPickedNY(); $nz = $e->xPickedNZ();
        $ax = abs($nx); $ay = abs($ny); $az = abs($nz);
        if ($ax >= $ay && $ax >= $az) { return [$nx < 0 ? -1 : 1, 0, 0]; }
        if ($ay >= $az)               { return [0, $ny < 0 ? -1 : 1, 0]; }
        return [0, 0, $nz < 0 ? -1 : 1];
    }

    // ============================================================ save / load

    private function worldFile(): string { return dirname(__DIR__, 2) . '/craft-world.json'; }

    private function saveWorld(): void
    {
        // infinite world: only the seed + player edits + which chunks have trees.
        // Terrain/ores regenerate procedurally from the seed.
        $data = ['seed' => $this->seed, 'edits' => $this->edits, 'treeGen' => array_keys($this->treeGen), 'inv' => $this->inv];
        $ok = @file_put_contents($this->worldFile(), json_encode($data)) !== false;
        $this->status = $ok ? 'World saved.' : 'Save failed.';
    }

    private function loadWorld(): void
    {
        $f = $this->worldFile();
        if (!is_file($f) || ($d = json_decode((string) file_get_contents($f), true)) === null) {
            $this->status = 'No saved world.';
            return;
        }
        $this->clearWorld();
        $this->seed = (float) ($d['seed'] ?? 0);
        $this->height = [];
        $this->biome = [];
        $this->edits = [];
        $this->editsByChunk = [];
        $this->lightCells = [];
        $this->treeGen = [];
        foreach (($d['treeGen'] ?? []) as $ck) { $this->treeGen[(string) $ck] = true; }
        foreach (($d['edits'] ?? []) as $k => $type) {
            [$x, $y, $z] = array_map('intval', explode(',', (string) $k));
            $this->setEdit($x, $y, $z, (int) $type);
        }
        $this->inv = [];
        foreach (($d['inv'] ?? []) as $t => $c) { $this->inv[(int) $t] = (int) $c; }
        if ($this->inv === []) { $this->starterKit(); } // older saves had no inventory
        $this->status = 'World loaded.'; // chunks stream in around the player on Play
    }

    // ==================================================================== menus

    private function mainMenu(): string
    {
        $items   = ['Play', 'New World', 'Save World', 'Load World', 'Settings', 'Quit'];
        $actions = ['play', 'new', 'save', 'load', 'settings', 'quit'];
        $sel = 0; $e = $this->e;
        $this->streamCX = PHP_INT_MAX;
        $this->updateStreaming($this->originX, $this->originZ); // queue the area around the map centre
        $shot = getenv('CRAFT_MENUSHOT'); $sf = 0;
        if ($shot) { $this->flushStreaming(); } // screenshots need the backdrop present at once

        while (true) {
            if ($this->closeRequested()) { $this->quit = true; return 'quit'; }
            if ($e->xKeyHit(Constants::KEY_UP))   { $sel = ($sel + count($items) - 1) % count($items); }
            if ($e->xKeyHit(Constants::KEY_DOWN)) { $sel = ($sel + 1) % count($items); }
            if ($e->xKeyHit(Constants::KEY_ESCAPE)) { return 'quit'; }
            if ($e->xKeyHit(Constants::KEY_RETURN)) { return $actions[$sel]; }

            $this->orbitBackdrop();
            $w = $e->xGraphicsWidth();
            $e->xColor(255, 255, 255);
            $e->xText($w / 2, 150, 'C R A F T', 1);
            $e->xColor(200, 220, 255);
            $e->xText($w / 2, 180, 'a voxel world for Xors3d (PHP / FFI)', 1);
            foreach ($items as $i => $label) {
                $e->xColor(...($i === $sel ? [255, 240, 120] : [210, 210, 210]));
                $e->xText($w / 2, 250 + $i * 32, $i === $sel ? "> $label <" : $label, 1);
            }
            if ($this->status !== '') {
                $e->xColor(120, 255, 160);
                $e->xText($w / 2, 250 + count($items) * 32 + 10, $this->status, 1);
            }
            $e->xColor(150, 150, 150);
            $e->xText($w / 2, $e->xGraphicsHeight() - 40, 'Arrows: move    Enter: select    Esc: quit', 1);
            if ($shot && ++$sf > 40) { $e->xSaveBuffer($e->xBackBuffer(), $shot); $this->quit = true; return 'quit'; }
            $e->xFlip();
        }
    }

    private function settingsMenu(): void
    {
        $opts = self::OPTIONS; $sel = 0; $e = $this->e;
        $shot = getenv('CRAFT_SETSHOT'); $sf = 0;

        while (true) {
            if ($this->closeRequested()) { $this->quit = true; return; }
            if ($e->xKeyHit(Constants::KEY_ESCAPE)) { $this->saveSettings(); return; }
            if ($e->xKeyHit(Constants::KEY_UP))   { $sel = ($sel + count($opts) - 1) % count($opts); }
            if ($e->xKeyHit(Constants::KEY_DOWN)) { $sel = ($sel + 1) % count($opts); }
            if ($e->xKeyHit(Constants::KEY_LEFT))  { $this->adjust($opts[$sel], -1); }
            if ($e->xKeyHit(Constants::KEY_RIGHT)) { $this->adjust($opts[$sel], +1); }

            $this->orbitBackdrop();
            $w = $e->xGraphicsWidth();
            $e->xColor(255, 255, 255);
            $e->xText($w / 2, 70, 'S E T T I N G S', 1);
            foreach ($opts as $i => $opt) {
                $note = isset($opt['note']) ? "  ({$opt['note']})" : '';
                $line = sprintf('%-18s  < %s >%s', $opt['label'], $this->valueText($opt), $note);
                $e->xColor(...($i === $sel ? [255, 240, 120] : [210, 210, 210]));
                $e->xText($w / 2, 130 + $i * 32, $line, 1);
            }
            $e->xColor(150, 150, 150);
            $e->xText($w / 2, $e->xGraphicsHeight() - 40, 'Up/Down: choose    Left/Right: change    Esc: back (saves)', 1);
            if ($shot && ++$sf > 40) { $e->xSaveBuffer($e->xBackBuffer(), $shot); $this->quit = true; return; }
            $e->xFlip();
        }
    }

    private function valueText(array $opt): string
    {
        $k = $opt['key'];
        return match ($opt['type']) {
            'bool'  => ((int) $this->settings[$k] ? 'On' : 'Off'),
            'int'   => (string) (int) $this->settings[$k],
            'float' => number_format((float) $this->settings[$k], 2),
            'res'   => (int) $this->settings['width'] . 'x' . (int) $this->settings['height'],
            default => (string) $this->settings[$k],
        };
    }

    private function adjust(array $opt, int $dir): void
    {
        $k = $opt['key'];
        switch ($opt['type']) {
            case 'bool':
                $this->settings[$k] = (int) !((int) $this->settings[$k]);
                break;
            case 'int':
                $this->settings[$k] = (int) max($opt['min'], min($opt['max'], (int) $this->settings[$k] + $dir * $opt['step']));
                break;
            case 'float':
                $v = (float) $this->settings[$k] + $dir * $opt['step'];
                $this->settings[$k] = round(max($opt['min'], min($opt['max'], $v)), 2);
                break;
            case 'res':
                $cur = 0;
                foreach (self::RESOLUTIONS as $i => [$rw, $rh]) {
                    if ((int) $this->settings['width'] === $rw && (int) $this->settings['height'] === $rh) { $cur = $i; }
                }
                $cur = ($cur + $dir + count(self::RESOLUTIONS)) % count(self::RESOLUTIONS);
                [$this->settings['width'], $this->settings['height']] = self::RESOLUTIONS[$cur];
                break;
        }
        $this->applySettings();
        $this->saveSettings();
    }

    private function orbitBackdrop(): void
    {
        $e = $this->e;
        $this->processStreaming(6, 2); // keep the backdrop filling in without a freeze
        $mid = $this->originX;
        $t = $e->xMillisecs() / 4000.0;
        $r = (int) $this->settings["renderDist"] * self::BLOCK * 0.5;
        $e->xPositionEntity($this->pivot, $mid, self::MAX_H * self::BLOCK, $mid);
        $e->xPositionEntity($this->camH, $mid + cos($t) * $r, (self::MAX_H + 6) * self::BLOCK, $mid + sin($t) * $r);
        $e->xPointEntity($this->camH, $this->pivot);
        $this->updateSky();
        $this->updateSkyObjects();
        $this->animateWater();
        $this->streamMobs();
        $this->updateMobs();
        $e->xRenderWorld();
    }

    // ================================================================ gameplay

    /** True if a solid (non-water) block occupies this voxel cell. */
    private function solidCell(int $bx, int $by, int $bz): bool
    {
        return $this->solidType($bx, $by, $bz) > 0;
    }

    private function cellOf(float $w): int
    {
        return (int) floor(($w + self::BLOCK / 2) / self::BLOCK);
    }

    private function move(): void
    {
        $e = $this->e;
        $fly = $this->fly;

        // direction from camera transform (so it follows where you look)
        $e->xTFormVector(0, 0, 1, $this->camH, 0);
        $fwx = $e->xTFormedX(); $fwy = $e->xTFormedY(); $fwz = $e->xTFormedZ();
        $e->xTFormVector(1, 0, 0, $this->camH, 0);
        $rgx = $e->xTFormedX(); $rgy = $e->xTFormedY(); $rgz = $e->xTFormedZ();

        if (!$fly) { // project onto XZ for walking
            $fl = hypot($fwx, $fwz) ?: 1.0; $fwx /= $fl; $fwz /= $fl; $fwy = 0.0;
            $rl = hypot($rgx, $rgz) ?: 1.0; $rgx /= $rl; $rgz /= $rl; $rgy = 0.0;
        }

        $spd = $fly ? self::SPD_FLY : self::SPD_WALK;
        $mx = $my = $mz = 0.0;
        if ($e->xKeyDown(Constants::KEY_W)) { $mx += $fwx; $my += $fwy; $mz += $fwz; }
        if ($e->xKeyDown(Constants::KEY_S)) { $mx -= $fwx; $my -= $fwy; $mz -= $fwz; }
        if ($e->xKeyDown(Constants::KEY_D)) { $mx += $rgx; $my += $rgy; $mz += $rgz; }
        if ($e->xKeyDown(Constants::KEY_A)) { $mx -= $rgx; $my -= $rgy; $mz -= $rgz; }
        $ml = hypot(hypot($mx, $my), $mz);
        if ($ml > 0.0) { $mx = $mx / $ml * $spd; $my = $my / $ml * $spd; $mz = $mz / $ml * $spd; }

        $moving = $ml > 0.0;

        $dt = $this->dt;
        if ($fly) {
            $this->px += $mx * $dt; $this->py += $my * $dt; $this->pz += $mz * $dt;
            if ($e->xKeyDown(Constants::KEY_SPACE))  { $this->py += $spd * $dt; }
            if ($e->xKeyDown(Constants::KEY_LSHIFT)) { $this->py -= $spd * $dt; }
        } else {
            $this->moveAxisX($mx * $dt);
            $this->moveAxisZ($mz * $dt);
            $this->applyGravity();
            if ($this->onGround && $e->xKeyHit(Constants::KEY_SPACE)) { $this->vy = self::JUMP; }
            // footsteps
            if ($moving && $this->onGround) {
                $now = $e->xMillisecs();
                if ($now - $this->lastStep > 340) { $this->play($this->sndStep); $this->lastStep = $now; }
            }
            if ($this->py < -30.0) { $this->spawnPlayer(); } // fell out of the world
        }

        $e->xPositionEntity($this->camH, $this->px, $this->py + self::EYE, $this->pz);
    }

    private function blockedAt(float $x, float $z): bool
    {
        $bx = $this->cellOf($x); $bz = $this->cellOf($z);
        $c1 = $this->cellOf($this->py + 0.2);
        $c2 = $this->cellOf($this->py + self::PH - 0.2);
        return $this->solidCell($bx, $c1, $bz) || $this->solidCell($bx, $c2, $bz);
    }

    private function moveAxisX(float $mx): void
    {
        if ($mx === 0.0) { return; }
        $tx = $this->px + $mx + ($mx > 0 ? self::HW : -self::HW);
        if (!$this->blockedAt($tx, $this->pz)) { $this->px += $mx; return; }
        // auto step-up: climb a 1-block rise (hills, stairs) if there is headroom
        if ($this->onGround && $this->canStepUp($tx, $this->pz)) {
            $this->py += self::BLOCK; $this->px += $mx;
        }
    }

    private function moveAxisZ(float $mz): void
    {
        if ($mz === 0.0) { return; }
        $tz = $this->pz + $mz + ($mz > 0 ? self::HW : -self::HW);
        if (!$this->blockedAt($this->px, $tz)) { $this->pz += $mz; return; }
        if ($this->onGround && $this->canStepUp($this->px, $tz)) {
            $this->py += self::BLOCK; $this->pz += $mz;
        }
    }

    /** True if a single block rise here can be climbed (block at feet, clear above). */
    private function canStepUp(float $x, float $z): bool
    {
        $bx = $this->cellOf($x); $bz = $this->cellOf($z);
        $feet = $this->cellOf($this->py + 0.2);
        if (!$this->solidCell($bx, $feet, $bz)) { return false; } // nothing to step onto
        // body must be clear one block higher
        $c1 = $this->cellOf($this->py + self::BLOCK + 0.2);
        $c2 = $this->cellOf($this->py + self::BLOCK + self::PH - 0.2);
        return !$this->solidCell($bx, $c1, $bz) && !$this->solidCell($bx, $c2, $bz);
    }

    private function applyGravity(): void
    {
        $dt = $this->dt;
        $this->vy -= self::G * $dt;
        $ny = $this->py + $this->vy * $dt;
        $bx = $this->cellOf($this->px); $bz = $this->cellOf($this->pz);

        if ($this->vy <= 0.0) {
            $fc = $this->cellOf($ny);
            if ($this->solidCell($bx, $fc, $bz)) {
                $this->py = $fc * self::BLOCK + self::BLOCK / 2 + 0.02;
                $this->vy = 0.0;
                $this->onGround = true;
                return;
            }
            $this->onGround = false;
        } else {
            $hc = $this->cellOf($this->py + self::PH + $this->vy * $dt);
            if ($this->solidCell($bx, $hc, $bz)) { $this->vy = 0.0; return; }
        }
        $this->py = $ny;
    }

    private function animateWater(): void
    {
        if ($this->waterTex === 0 || $this->water === []) { return; }
        $frame = (int) ($this->e->xMillisecs() / 90) % 32;
        foreach (array_keys($this->water) as $w) {
            $this->e->xEntityTexture($w, $this->waterTex, $frame);
        }
    }

    private function gameLoop(int $max): void
    {
        $e = $this->e; $h = $this->camH; $frame = 0;
        $this->lastMs = PHP_INT_MIN;

        while (true) {
            if ($this->closeRequested()) { $this->quit = true; return; }
            if ($max === 0 && $e->xKeyHit(Constants::KEY_ESCAPE)) { return; }

            // Frame time in "60 FPS-frame" units. xMillisecs() is a SIGNED 32-bit ms
            // counter and goes negative after ~24.8 days of uptime, so never test it with
            // "> 0"; use a sentinel for the first frame and treat a negative/huge delta
            // (wrap or hitch) as one frame.
            $now = $e->xMillisecs();
            $frameMs = ($this->lastMs === PHP_INT_MIN) ? 16 : ($now - $this->lastMs);
            $this->lastMs = $now;
            if ($frameMs < 0 || $frameMs > 250) { $frameMs = 16; }
            $frameDt = min(3.0, $frameMs / 16.6667);

            if ($e->xKeyHit(Constants::KEY_F)) { $this->fly = !$this->fly; $this->vy = 0.0; }

            $this->cam->lookOnly();

            // Fixed-timestep physics: run movement/collision/gravity in constant 1/60 s
            // steps regardless of render FPS. This keeps speed AND collision behaviour
            // identical at 60 or 440+ FPS (collision look-ahead no longer scales with the
            // frame's step size). Leftover time carries to the next frame; capped to avoid
            // a spiral of death after a big hitch.
            $this->acc += $frameDt;
            $this->dt = 1.0;
            $steps = 0;
            while ($this->acc >= 1.0 && $steps < 5) {
                $this->move();
                $this->acc -= 1.0;
                $steps++;
            }
            $this->dt = $frameDt; // restore real frame dt for per-frame visuals below

            $this->updateStreaming($this->px, $this->pz);
            $this->processStreaming(2, 2); // budgeted: build a few chunks/frame, no hitches
            $this->animateWater();
            $this->streamMobs();
            $this->updateMobs();

            // block selection: number keys 1-9 (first nine) + mouse wheel (all)
            for ($n = 1; $n <= min(9, count($this->hotbar)); $n++) {
                if ($e->xKeyHit(Constants::KEY_1 + ($n - 1))) { $this->slot = $n - 1; $this->refreshHand($e); }
            }
            $wheel = $e->xMouseZSpeed();
            if ($wheel !== 0) {
                $c = count($this->hotbar);
                $this->slot = (($this->slot - ($wheel > 0 ? 1 : -1)) % $c + $c) % $c;
                $this->refreshHand($e);
            }
            $e->xTurnEntity($this->hand, 0, 1.5 * $this->dt, 0);
            $this->updateSky();
            $this->updateSkyObjects();
            $this->updateWeather();
            $this->updatePuddles();
            $this->updateParticles();
            $this->updatePointLights();

            $cx = (int) ($e->xGraphicsWidth() / 2);
            $cy = (int) ($e->xGraphicsHeight() / 2);
            $e->xCameraPick($h, $cx, $cy);
            $picked = $e->xPickedEntity();
            $hasTarget = $picked !== 0 && isset($this->meshCk[$picked]);

            if ($hasTarget) {
                // pick point + face normal -> the block cell just inside / outside the face
                $px = $e->xPickedX(); $py = $e->xPickedY(); $pz = $e->xPickedZ();
                [$dx, $dy, $dz] = $this->faceOffset($e);
                $q = self::BLOCK * 0.25;
                if ($e->xMouseHit(1)) {
                    $bx = $this->cellOf($px - $dx * $q);
                    $by = $this->cellOf($py - $dy * $q);
                    $bz = $this->cellOf($pz - $dz * $q);
                    $this->destroyAt($e, $bx, $by, $bz);
                } elseif ($e->xMouseHit(2) || $e->xMouseHit(3)) {
                    $bx = $this->cellOf($px + $dx * $q);
                    $by = $this->cellOf($py + $dy * $q);
                    $bz = $this->cellOf($pz + $dz * $q);
                    $this->placeAt($e, $bx, $by, $bz, $this->selectedType());
                } elseif ($e->xKeyHit(Constants::KEY_E)) {
                    // E opens/closes the targeted door
                    $bx = $this->cellOf($px - $dx * $q);
                    $by = $this->cellOf($py - $dy * $q);
                    $bz = $this->cellOf($pz - $dz * $q);
                    $this->toggleDoor($bx, $by, $bz);
                }
            }

            // C opens the crafting / block menu (assigns a block to the active slot)
            if ($e->xKeyHit(Constants::KEY_C)) { $this->craftMenu(); }

            if ($max > 0 && getenv('CRAFT_LOOKUP')) { $e->xRotateEntity($h, -40, 40, 0); }

            $e->xRenderWorld();
            $this->renderGodRays();
            $this->renderBloom();
            $this->drawHud($e, $hasTarget);

            if ($max > 0 && $frame + 1 >= $max && ($shot = getenv('CRAFT_SHOT'))) {
                $e->xSaveBuffer($e->xBackBuffer(), $shot);
            }
            $e->xFlip();
            if ($max > 0 && ++$frame >= $max) { return; }
        }
    }

    private function drawHud(Engine $e, bool $hasTarget): void
    {
        $w = $e->xGraphicsWidth();
        $cx = (int) ($w / 2);
        $cy = (int) ($e->xGraphicsHeight() / 2);

        // crosshair (two lines)
        $e->xColor(255, 255, 255);
        $e->xLine($cx - 9, $cy, $cx + 9, $cy);
        $e->xLine($cx, $cy - 9, $cx, $cy + 9);

        $e->xColor(255, 255, 0);
        $e->xText(10, 10, 'FPS: ' . $e->xGetFPS());
        $e->xColor(220, 220, 220);
        $e->xText(10, 30, 'Chunks: ' . count($this->chunkMesh) . '   Mobs: ' . count($this->mobs));
        $e->xText(10, 50, 'Mode: ' . ($this->fly ? 'Fly (F)' : 'Walk (F)'));
        $e->xText(10, 70, $hasTarget ? 'LMB destroy / RMB place / E door' : 'no target');
        $e->xText(10, 90, 'C: craft menu    Esc: menu');

        // visual hotbar: block icons with a selection frame
        $slots = count($this->hotbar);
        $cell = 52; $pad = 4; $iw = 44;
        $barW = $slots * $cell;
        $x0 = $cx - (int) ($barW / 2);
        $y0 = $e->xGraphicsHeight() - $cell - 8;
        foreach ($this->hotbar as $i => $id) {
            $sx = $x0 + $i * $cell;
            $cnt = $this->invCount($id);
            $e->xColor(20, 20, 20);
            $e->xRect($sx, $y0, $cell - 2, $cell - 2, 1);             // slot background
            $e->xDrawImage($this->icon[$id], $sx + $pad, $y0 + $pad);  // block icon
            if ($i === $this->slot) {
                $e->xColor(255, 255, 255);
                $e->xRect($sx - 1, $y0 - 1, $cell, $cell, 0);          // selection frame
            }
            $e->xColor(200, 200, 200);
            $e->xText($sx + 4, $y0 + 2, (string) ($i + 1));            // slot number
            // held count (bottom-right), red when empty
            if ($cnt > 0) { $e->xColor(255, 255, 255); } else { $e->xColor(210, 90, 90); }
            $e->xText($sx + $cell - 22, $y0 + $cell - 18, (string) $cnt);
        }
        // selected block name
        $e->xColor(255, 255, 255);
        $e->xText($cx, $y0 - 18, self::TYPES[$this->selectedType()][0], 1);
    }

}
