.lib "xscript.dll"

xLoadScript%(fileName$):"_xLoadScript@4"
xExecuteScript%(script%, entryPoint$):"_xExecuteScript@8"
xDeleteScript(script%):"_xDeleteScript@4"
xSetIntegerVariable(script%, varName$, value%):"_xSetIntegerVariable@12"
xGetIntegerVariable%(script%, varName$):"_xGetIntegerVariable@8"
xSetFloatVariable(script%, varName$, value#):"_xSetFloatVariable@12"
xGetFloatVariable#(script%, varName$):"_xGetFloatVariable@8"
xSetStringVariable(script%, varName$, value$):"_xSetStringVariable@12"
xGetStringVariable$(script%, varName$):"_xGetStringVariable@8"
xRegisterFunction(decl$, funcAddr%):"_xRegisterFunction@8"
xSetIntegerArg(index%, value%):"_xSetIntegerArg@8"
xSetFloatArg(index%, value#):"_xSetFloatArg@8"
xSetStringArg(index%, value$):"_xSetStringArg@8"
xGetIntegerReturn%():"_xGetIntegerReturn@0"
xGetFloatReturn#():"_xGetFloatReturn@0"
xGetStringReturn$():"_xGetStringReturn@0"
xCreateScript%(data%, length%):"_xCreateScript@8"